// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: errors_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码枚举
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_SUCCESS ErrorCode = 0 // 成功（默认值，0 表示成功）
	// 通用错误码 (1000-1999)
	ErrorCode_ERROR_CODE_INTERNAL_ERROR  ErrorCode = 1001 // 内部错误
	ErrorCode_ERROR_CODE_INVALID_MESSAGE ErrorCode = 1002 // 无效消息
	ErrorCode_ERROR_CODE_AUTH_REQUIRED   ErrorCode = 1003 // 需要认证
	ErrorCode_ERROR_CODE_INVALID_TOKEN   ErrorCode = 1004 // 无效 token
	// 认证相关错误 (2000-2999)
	ErrorCode_ERROR_CODE_AUTH_FAILED   ErrorCode = 2001 // 认证失败
	ErrorCode_ERROR_CODE_TOKEN_EXPIRED ErrorCode = 2002 // Token 过期
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "ERROR_CODE_SUCCESS",
		1001: "ERROR_CODE_INTERNAL_ERROR",
		1002: "ERROR_CODE_INVALID_MESSAGE",
		1003: "ERROR_CODE_AUTH_REQUIRED",
		1004: "ERROR_CODE_INVALID_TOKEN",
		2001: "ERROR_CODE_AUTH_FAILED",
		2002: "ERROR_CODE_TOKEN_EXPIRED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_SUCCESS":         0,
		"ERROR_CODE_INTERNAL_ERROR":  1001,
		"ERROR_CODE_INVALID_MESSAGE": 1002,
		"ERROR_CODE_AUTH_REQUIRED":   1003,
		"ERROR_CODE_INVALID_TOKEN":   1004,
		"ERROR_CODE_AUTH_FAILED":     2001,
		"ERROR_CODE_TOKEN_EXPIRED":   2002,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_msg_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_msg_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_msg_proto_rawDescGZIP(), []int{0}
}

// MessageID 枚举 - 定义所有消息 ID
// 注意：请求和响应使用相同的消息 ID
type MessageID int32

const (
	MessageID_MSG_ID_UNKNOWN MessageID = 0
	// 请求消息 ID（请求和响应共用）
	MessageID_MSG_ID_AUTH_REQUEST MessageID = 1 // 认证请求/响应
	MessageID_MSG_ID_PING_REQUEST MessageID = 4 // 心跳请求/响应（Pong）
)

// Enum value maps for MessageID.
var (
	MessageID_name = map[int32]string{
		0: "MSG_ID_UNKNOWN",
		1: "MSG_ID_AUTH_REQUEST",
		4: "MSG_ID_PING_REQUEST",
	}
	MessageID_value = map[string]int32{
		"MSG_ID_UNKNOWN":      0,
		"MSG_ID_AUTH_REQUEST": 1,
		"MSG_ID_PING_REQUEST": 4,
	}
)

func (x MessageID) Enum() *MessageID {
	p := new(MessageID)
	*p = x
	return p
}

func (x MessageID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageID) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_msg_proto_enumTypes[1].Descriptor()
}

func (MessageID) Type() protoreflect.EnumType {
	return &file_errors_msg_proto_enumTypes[1]
}

func (x MessageID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageID.Descriptor instead.
func (MessageID) EnumDescriptor() ([]byte, []int) {
	return file_errors_msg_proto_rawDescGZIP(), []int{1}
}

var File_errors_msg_proto protoreflect.FileDescriptor

const file_errors_msg_proto_rawDesc = "" +
	"\n" +
	"\x10errors_msg.proto*\xde\x01\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_SUCCESS\x10\x00\x12\x1e\n" +
	"\x19ERROR_CODE_INTERNAL_ERROR\x10\xe9\a\x12\x1f\n" +
	"\x1aERROR_CODE_INVALID_MESSAGE\x10\xea\a\x12\x1d\n" +
	"\x18ERROR_CODE_AUTH_REQUIRED\x10\xeb\a\x12\x1d\n" +
	"\x18ERROR_CODE_INVALID_TOKEN\x10\xec\a\x12\x1b\n" +
	"\x16ERROR_CODE_AUTH_FAILED\x10\xd1\x0f\x12\x1d\n" +
	"\x18ERROR_CODE_TOKEN_EXPIRED\x10\xd2\x0f*Q\n" +
	"\tMessageID\x12\x12\n" +
	"\x0eMSG_ID_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13MSG_ID_AUTH_REQUEST\x10\x01\x12\x17\n" +
	"\x13MSG_ID_PING_REQUEST\x10\x04B\rZ\vwx_game/msgb\x06proto3"

var (
	file_errors_msg_proto_rawDescOnce sync.Once
	file_errors_msg_proto_rawDescData []byte
)

func file_errors_msg_proto_rawDescGZIP() []byte {
	file_errors_msg_proto_rawDescOnce.Do(func() {
		file_errors_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_msg_proto_rawDesc), len(file_errors_msg_proto_rawDesc)))
	})
	return file_errors_msg_proto_rawDescData
}

var file_errors_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errors_msg_proto_goTypes = []any{
	(ErrorCode)(0), // 0: ErrorCode
	(MessageID)(0), // 1: MessageID
}
var file_errors_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_msg_proto_init() }
func file_errors_msg_proto_init() {
	if File_errors_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_msg_proto_rawDesc), len(file_errors_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_msg_proto_goTypes,
		DependencyIndexes: file_errors_msg_proto_depIdxs,
		EnumInfos:         file_errors_msg_proto_enumTypes,
	}.Build()
	File_errors_msg_proto = out.File
	file_errors_msg_proto_goTypes = nil
	file_errors_msg_proto_depIdxs = nil
}
