// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: errors_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码枚举
type ErrorCode int32

const (
	ErrorCode_E_ErrorCode_None ErrorCode = 0 // 成功（默认值，0 表示成功）
	// 通用错误码 (10000-11000)
	ErrorCode_E_ErrorCode_Internal     ErrorCode = 10001 // 内部错误
	ErrorCode_E_ErrorCode_InvalidMsg   ErrorCode = 10002 // 无效消息
	ErrorCode_E_ErrorCode_AuthRequired ErrorCode = 10003 // 需要认证
	ErrorCode_E_ErrorCode_InvalidToken ErrorCode = 10004 // 无效 token
	ErrorCode_E_ErrorCode_AuthFailed   ErrorCode = 10005 // 认证失败
	ErrorCode_E_ErrorCode_TokenExpired ErrorCode = 10006 // Token 过期
	// [活动]合成大西瓜[20000, 20100]
	ErrorCode_E_ErrorCode_Activity_WaterMelon_BuyNumLimit       ErrorCode = 20001 // [活动]合成大西瓜礼包购买达到上限
	ErrorCode_E_ErrorCode_Activity_WaterMelon_Condition         ErrorCode = 20002 // [活动]合成大西瓜条件错误
	ErrorCode_E_ErrorCode_Activity_WaterMelon_Parameter         ErrorCode = 20003 // [活动]合成大西瓜参数错误
	ErrorCode_E_ErrorCode_Activity_WaterMelon_Purchased         ErrorCode = 20004 // [活动]合成大西瓜已购买
	ErrorCode_E_ErrorCode_Activity_WaterMelon_NotRewardClaim    ErrorCode = 20005 // [活动]合成大西瓜无可领取的奖励
	ErrorCode_E_ErrorCode_Activity_WaterMelon_StaminaNotEnough  ErrorCode = 20006 // [活动]合成大西瓜体力不足
	ErrorCode_E_ErrorCode_Activity_WaterMelon_UseItemCountLimit ErrorCode = 20007 // [活动]合成大西瓜道具使用数量限制
	ErrorCode_E_ErrorCode_Activity_WaterMelon_Cfg               ErrorCode = 20008 //配置表错误
	ErrorCode_E_ErrorCode_Activity_WaterMelon_Logic             ErrorCode = 20009 //内部逻辑错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "E_ErrorCode_None",
		10001: "E_ErrorCode_Internal",
		10002: "E_ErrorCode_InvalidMsg",
		10003: "E_ErrorCode_AuthRequired",
		10004: "E_ErrorCode_InvalidToken",
		10005: "E_ErrorCode_AuthFailed",
		10006: "E_ErrorCode_TokenExpired",
		20001: "E_ErrorCode_Activity_WaterMelon_BuyNumLimit",
		20002: "E_ErrorCode_Activity_WaterMelon_Condition",
		20003: "E_ErrorCode_Activity_WaterMelon_Parameter",
		20004: "E_ErrorCode_Activity_WaterMelon_Purchased",
		20005: "E_ErrorCode_Activity_WaterMelon_NotRewardClaim",
		20006: "E_ErrorCode_Activity_WaterMelon_StaminaNotEnough",
		20007: "E_ErrorCode_Activity_WaterMelon_UseItemCountLimit",
		20008: "E_ErrorCode_Activity_WaterMelon_Cfg",
		20009: "E_ErrorCode_Activity_WaterMelon_Logic",
	}
	ErrorCode_value = map[string]int32{
		"E_ErrorCode_None":                                  0,
		"E_ErrorCode_Internal":                              10001,
		"E_ErrorCode_InvalidMsg":                            10002,
		"E_ErrorCode_AuthRequired":                          10003,
		"E_ErrorCode_InvalidToken":                          10004,
		"E_ErrorCode_AuthFailed":                            10005,
		"E_ErrorCode_TokenExpired":                          10006,
		"E_ErrorCode_Activity_WaterMelon_BuyNumLimit":       20001,
		"E_ErrorCode_Activity_WaterMelon_Condition":         20002,
		"E_ErrorCode_Activity_WaterMelon_Parameter":         20003,
		"E_ErrorCode_Activity_WaterMelon_Purchased":         20004,
		"E_ErrorCode_Activity_WaterMelon_NotRewardClaim":    20005,
		"E_ErrorCode_Activity_WaterMelon_StaminaNotEnough":  20006,
		"E_ErrorCode_Activity_WaterMelon_UseItemCountLimit": 20007,
		"E_ErrorCode_Activity_WaterMelon_Cfg":               20008,
		"E_ErrorCode_Activity_WaterMelon_Logic":             20009,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_msg_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_msg_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_msg_proto_rawDescGZIP(), []int{0}
}

type MSG_ERROR_CODE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSG_ERROR_CODE) Reset() {
	*x = MSG_ERROR_CODE{}
	mi := &file_errors_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSG_ERROR_CODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_ERROR_CODE) ProtoMessage() {}

func (x *MSG_ERROR_CODE) ProtoReflect() protoreflect.Message {
	mi := &file_errors_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_ERROR_CODE.ProtoReflect.Descriptor instead.
func (*MSG_ERROR_CODE) Descriptor() ([]byte, []int) {
	return file_errors_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_ERROR_CODE) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_errors_msg_proto protoreflect.FileDescriptor

const file_errors_msg_proto_rawDesc = "" +
	"\n" +
	"\x10errors_msg.proto\"/\n" +
	"\x0eMSG_ERROR_CODE\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode*\x98\x05\n" +
	"\tErrorCode\x12\x14\n" +
	"\x10E_ErrorCode_None\x10\x00\x12\x19\n" +
	"\x14E_ErrorCode_Internal\x10\x91N\x12\x1b\n" +
	"\x16E_ErrorCode_InvalidMsg\x10\x92N\x12\x1d\n" +
	"\x18E_ErrorCode_AuthRequired\x10\x93N\x12\x1d\n" +
	"\x18E_ErrorCode_InvalidToken\x10\x94N\x12\x1b\n" +
	"\x16E_ErrorCode_AuthFailed\x10\x95N\x12\x1d\n" +
	"\x18E_ErrorCode_TokenExpired\x10\x96N\x121\n" +
	"+E_ErrorCode_Activity_WaterMelon_BuyNumLimit\x10\xa1\x9c\x01\x12/\n" +
	")E_ErrorCode_Activity_WaterMelon_Condition\x10\xa2\x9c\x01\x12/\n" +
	")E_ErrorCode_Activity_WaterMelon_Parameter\x10\xa3\x9c\x01\x12/\n" +
	")E_ErrorCode_Activity_WaterMelon_Purchased\x10\xa4\x9c\x01\x124\n" +
	".E_ErrorCode_Activity_WaterMelon_NotRewardClaim\x10\xa5\x9c\x01\x126\n" +
	"0E_ErrorCode_Activity_WaterMelon_StaminaNotEnough\x10\xa6\x9c\x01\x127\n" +
	"1E_ErrorCode_Activity_WaterMelon_UseItemCountLimit\x10\xa7\x9c\x01\x12)\n" +
	"#E_ErrorCode_Activity_WaterMelon_Cfg\x10\xa8\x9c\x01\x12+\n" +
	"%E_ErrorCode_Activity_WaterMelon_Logic\x10\xa9\x9c\x01B Z\vwx_game/msg\xaa\x02\x10Net.Proto.Errorsb\x06proto3"

var (
	file_errors_msg_proto_rawDescOnce sync.Once
	file_errors_msg_proto_rawDescData []byte
)

func file_errors_msg_proto_rawDescGZIP() []byte {
	file_errors_msg_proto_rawDescOnce.Do(func() {
		file_errors_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_msg_proto_rawDesc), len(file_errors_msg_proto_rawDesc)))
	})
	return file_errors_msg_proto_rawDescData
}

var file_errors_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_msg_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: ErrorCode
	(*MSG_ERROR_CODE)(nil), // 1: MSG_ERROR_CODE
}
var file_errors_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_msg_proto_init() }
func file_errors_msg_proto_init() {
	if File_errors_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_msg_proto_rawDesc), len(file_errors_msg_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_msg_proto_goTypes,
		DependencyIndexes: file_errors_msg_proto_depIdxs,
		EnumInfos:         file_errors_msg_proto_enumTypes,
		MessageInfos:      file_errors_msg_proto_msgTypes,
	}.Build()
	File_errors_msg_proto = out.File
	file_errors_msg_proto_goTypes = nil
	file_errors_msg_proto_depIdxs = nil
}
