// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: item_server_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 背包
type DBItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	MapItem       map[int32]int32        `protobuf:"bytes,2,rep,name=map_item,json=mapItem,proto3" json:"map_item,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBItem) Reset() {
	*x = DBItem{}
	mi := &file_item_server_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBItem) ProtoMessage() {}

func (x *DBItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_server_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBItem.ProtoReflect.Descriptor instead.
func (*DBItem) Descriptor() ([]byte, []int) {
	return file_item_server_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DBItem) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DBItem) GetMapItem() map[int32]int32 {
	if x != nil {
		return x.MapItem
	}
	return nil
}

var File_item_server_msg_proto protoreflect.FileDescriptor

const file_item_server_msg_proto_rawDesc = "" +
	"\n" +
	"\x15item_server_msg.proto\"\x8e\x01\n" +
	"\x06DBItem\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12/\n" +
	"\bmap_item\x18\x02 \x03(\v2\x14.DBItem.MapItemEntryR\amapItem\x1a:\n" +
	"\fMapItemEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\x1fZ\vwx_game/msg\xaa\x02\x0fNet.Proto.Loginb\x06proto3"

var (
	file_item_server_msg_proto_rawDescOnce sync.Once
	file_item_server_msg_proto_rawDescData []byte
)

func file_item_server_msg_proto_rawDescGZIP() []byte {
	file_item_server_msg_proto_rawDescOnce.Do(func() {
		file_item_server_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_server_msg_proto_rawDesc), len(file_item_server_msg_proto_rawDesc)))
	})
	return file_item_server_msg_proto_rawDescData
}

var file_item_server_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_server_msg_proto_goTypes = []any{
	(*DBItem)(nil), // 0: DBItem
	nil,            // 1: DBItem.MapItemEntry
}
var file_item_server_msg_proto_depIdxs = []int32{
	1, // 0: DBItem.map_item:type_name -> DBItem.MapItemEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_server_msg_proto_init() }
func file_item_server_msg_proto_init() {
	if File_item_server_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_server_msg_proto_rawDesc), len(file_item_server_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_server_msg_proto_goTypes,
		DependencyIndexes: file_item_server_msg_proto_depIdxs,
		MessageInfos:      file_item_server_msg_proto_msgTypes,
	}.Build()
	File_item_server_msg_proto = out.File
	file_item_server_msg_proto_goTypes = nil
	file_item_server_msg_proto_depIdxs = nil
}
