// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: login_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登入验证
type LoginAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAuth) Reset() {
	*x = LoginAuth{}
	mi := &file_login_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAuth) ProtoMessage() {}

func (x *LoginAuth) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAuth.ProtoReflect.Descriptor instead.
func (*LoginAuth) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{0}
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_login_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{1}
}

// 踢人包
type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_login_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{2}
}

// 玩家bug反馈
type BugFeedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BugFeedback) Reset() {
	*x = BugFeedback{}
	mi := &file_login_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BugFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BugFeedback) ProtoMessage() {}

func (x *BugFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BugFeedback.ProtoReflect.Descriptor instead.
func (*BugFeedback) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{3}
}

type LoginAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAuthRequest) Reset() {
	*x = LoginAuthRequest{}
	mi := &file_login_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAuthRequest) ProtoMessage() {}

func (x *LoginAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAuthRequest.ProtoReflect.Descriptor instead.
func (*LoginAuthRequest) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoginAuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`    // 错误码（第一个字段固定）
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 认证状态，通常为 "authenticated"
	Role          *RoleBase              `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`     //角色信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAuthResponse) Reset() {
	*x = LoginAuthResponse{}
	mi := &file_login_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAuthResponse) ProtoMessage() {}

func (x *LoginAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAuthResponse.ProtoReflect.Descriptor instead.
func (*LoginAuthResponse) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoginAuthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginAuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginAuthResponse) GetRole() *RoleBase {
	if x != nil {
		return x.Role
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_login_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{1, 0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 错误码（第一个字段固定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_login_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type KickNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNotify) Reset() {
	*x = KickNotify{}
	mi := &file_login_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNotify) ProtoMessage() {}

func (x *KickNotify) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNotify.ProtoReflect.Descriptor instead.
func (*KickNotify) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{2, 0}
}

func (x *KickNotify) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type BugFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BugFeedbackRequest) Reset() {
	*x = BugFeedbackRequest{}
	mi := &file_login_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BugFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BugFeedbackRequest) ProtoMessage() {}

func (x *BugFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BugFeedbackRequest.ProtoReflect.Descriptor instead.
func (*BugFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BugFeedbackRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BugFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BugFeedbackResponse) Reset() {
	*x = BugFeedbackResponse{}
	mi := &file_login_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BugFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BugFeedbackResponse) ProtoMessage() {}

func (x *BugFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BugFeedbackResponse.ProtoReflect.Descriptor instead.
func (*BugFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_login_msg_proto_rawDescGZIP(), []int{3, 1}
}

func (x *BugFeedbackResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_login_msg_proto protoreflect.FileDescriptor

const file_login_msg_proto_rawDesc = "" +
	"\n" +
	"\x0flogin_msg.proto\x1a\x0erole_msg.proto\"\x8e\x01\n" +
	"\n" +
	"login_auth\x1a\x1f\n" +
	"\arequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x1a_\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x04role\x18\x03 \x01(\v2\x13.role_msg.role_baseR\x04role\"1\n" +
	"\x04ping\x1a\t\n" +
	"\arequest\x1a\x1e\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"$\n" +
	"\x04kick\x1a\x1c\n" +
	"\x06notify\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"K\n" +
	"\fbug_feedback\x1a\x1b\n" +
	"\arequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x1a\x1e\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04codeB\x1fZ\vwx_game/msg\xaa\x02\x0fNet.Proto.Loginb\x06proto3"

var (
	file_login_msg_proto_rawDescOnce sync.Once
	file_login_msg_proto_rawDescData []byte
)

func file_login_msg_proto_rawDescGZIP() []byte {
	file_login_msg_proto_rawDescOnce.Do(func() {
		file_login_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_msg_proto_rawDesc), len(file_login_msg_proto_rawDesc)))
	})
	return file_login_msg_proto_rawDescData
}

var file_login_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_login_msg_proto_goTypes = []any{
	(*LoginAuth)(nil),           // 0: login_auth
	(*Ping)(nil),                // 1: ping
	(*Kick)(nil),                // 2: kick
	(*BugFeedback)(nil),         // 3: bug_feedback
	(*LoginAuthRequest)(nil),    // 4: login_auth.request
	(*LoginAuthResponse)(nil),   // 5: login_auth.response
	(*PingRequest)(nil),         // 6: ping.request
	(*PingResponse)(nil),        // 7: ping.response
	(*KickNotify)(nil),          // 8: kick.notify
	(*BugFeedbackRequest)(nil),  // 9: bug_feedback.request
	(*BugFeedbackResponse)(nil), // 10: bug_feedback.response
	(*RoleBase)(nil),            // 11: role_msg.role_base
}
var file_login_msg_proto_depIdxs = []int32{
	11, // 0: login_auth.response.role:type_name -> role_msg.role_base
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_login_msg_proto_init() }
func file_login_msg_proto_init() {
	if File_login_msg_proto != nil {
		return
	}
	file_role_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_msg_proto_rawDesc), len(file_login_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_msg_proto_goTypes,
		DependencyIndexes: file_login_msg_proto_depIdxs,
		MessageInfos:      file_login_msg_proto_msgTypes,
	}.Build()
	File_login_msg_proto = out.File
	file_login_msg_proto_goTypes = nil
	file_login_msg_proto_depIdxs = nil
}
