// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rank_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_rank_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_rank_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_rank_msg_proto_rawDescGZIP(), []int{0}
}

// 头像信息
type RankStRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`         // 角色ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 角色名字
	AvatarId      int32                  `protobuf:"varint,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`   // 角色头像id
	FrameId       int32                  `protobuf:"varint,4,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`      //头像框id
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` //自定义头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankStRole) Reset() {
	*x = RankStRole{}
	mi := &file_rank_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankStRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankStRole) ProtoMessage() {}

func (x *RankStRole) ProtoReflect() protoreflect.Message {
	mi := &file_rank_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankStRole.ProtoReflect.Descriptor instead.
func (*RankStRole) Descriptor() ([]byte, []int) {
	return file_rank_msg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RankStRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RankStRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RankStRole) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *RankStRole) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RankStRole) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 排行元素
type RankStItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`     //排名 (从1开始)
	Role          *RankStRole            `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`      //头像信息
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`   // 分数
	Score2        int64                  `protobuf:"varint,4,opt,name=score2,proto3" json:"score2,omitempty"` // 分数2 (时间搓 负数正序)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankStItem) Reset() {
	*x = RankStItem{}
	mi := &file_rank_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankStItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankStItem) ProtoMessage() {}

func (x *RankStItem) ProtoReflect() protoreflect.Message {
	mi := &file_rank_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankStItem.ProtoReflect.Descriptor instead.
func (*RankStItem) Descriptor() ([]byte, []int) {
	return file_rank_msg_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RankStItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankStItem) GetRole() *RankStRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RankStItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankStItem) GetScore2() int64 {
	if x != nil {
		return x.Score2
	}
	return 0
}

// 排行请求
type RankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"` // 排行类型
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 页数(从0开始)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	mi := &file_rank_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rank_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_rank_msg_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RankRequest) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *RankRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// 排行响应
type RankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                 // 错误码（第一个字段固定）
	TotalPage     int32                  `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`      // 总页数
	NumPerPage    int32                  `protobuf:"varint,3,opt,name=num_per_page,json=numPerPage,proto3" json:"num_per_page,omitempty"` // 每页数量
	Items         []*RankStItem          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                // 排行数据
	Self          *RankStItem            `protobuf:"bytes,5,opt,name=self,proto3" json:"self,omitempty"`                                  //自己排行数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	mi := &file_rank_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rank_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_rank_msg_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RankResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RankResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *RankResponse) GetNumPerPage() int32 {
	if x != nil {
		return x.NumPerPage
	}
	return 0
}

func (x *RankResponse) GetItems() []*RankStItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RankResponse) GetSelf() *RankStItem {
	if x != nil {
		return x.Self
	}
	return nil
}

var File_rank_msg_proto protoreflect.FileDescriptor

const file_rank_msg_proto_rawDesc = "" +
	"\n" +
	"\x0erank_msg.proto\"\xec\x03\n" +
	"\x04rank\x1a\x8d\x01\n" +
	"\ast_role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\x05R\bavatarId\x12\x19\n" +
	"\bframe_id\x18\x04 \x01(\x05R\aframeId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x1an\n" +
	"\ast_item\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12!\n" +
	"\x04role\x18\x02 \x01(\v2\r.rank.st_roleR\x04role\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x16\n" +
	"\x06score2\x18\x04 \x01(\x03R\x06score2\x1a:\n" +
	"\arequest\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\x05R\brankType\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x1a\xa7\x01\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"total_page\x18\x02 \x01(\x05R\ttotalPage\x12 \n" +
	"\fnum_per_page\x18\x03 \x01(\x05R\n" +
	"numPerPage\x12#\n" +
	"\x05items\x18\x04 \x03(\v2\r.rank.st_itemR\x05items\x12!\n" +
	"\x04self\x18\x05 \x01(\v2\r.rank.st_itemR\x04selfB\x1eZ\vwx_game/msg\xaa\x02\x0eNet.Proto.Rankb\x06proto3"

var (
	file_rank_msg_proto_rawDescOnce sync.Once
	file_rank_msg_proto_rawDescData []byte
)

func file_rank_msg_proto_rawDescGZIP() []byte {
	file_rank_msg_proto_rawDescOnce.Do(func() {
		file_rank_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rank_msg_proto_rawDesc), len(file_rank_msg_proto_rawDesc)))
	})
	return file_rank_msg_proto_rawDescData
}

var file_rank_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rank_msg_proto_goTypes = []any{
	(*Rank)(nil),         // 0: rank
	(*RankStRole)(nil),   // 1: rank.st_role
	(*RankStItem)(nil),   // 2: rank.st_item
	(*RankRequest)(nil),  // 3: rank.request
	(*RankResponse)(nil), // 4: rank.response
}
var file_rank_msg_proto_depIdxs = []int32{
	1, // 0: rank.st_item.role:type_name -> rank.st_role
	2, // 1: rank.response.items:type_name -> rank.st_item
	2, // 2: rank.response.self:type_name -> rank.st_item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rank_msg_proto_init() }
func file_rank_msg_proto_init() {
	if File_rank_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rank_msg_proto_rawDesc), len(file_rank_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rank_msg_proto_goTypes,
		DependencyIndexes: file_rank_msg_proto_depIdxs,
		MessageInfos:      file_rank_msg_proto_msgTypes,
	}.Build()
	File_rank_msg_proto = out.File
	file_rank_msg_proto_goTypes = nil
	file_rank_msg_proto_depIdxs = nil
}
