// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: role_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色基础信息
type RoleBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RegisterTm    int64                  `protobuf:"varint,2,opt,name=register_tm,json=registerTm,proto3" json:"register_tm,omitempty"` //角色注册时间戳
	AvatarId      int32                  `protobuf:"varint,4,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`       // 角色头像id
	FrameId       int32                  `protobuf:"varint,5,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`          //头像框id
	Step          int32                  `protobuf:"varint,6,opt,name=step,proto3" json:"step,omitempty"`                               //引导步骤
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`                               // 角色名字
	AvatarUrl     string                 `protobuf:"bytes,11,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`    //自定义头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBase) Reset() {
	*x = RoleBase{}
	mi := &file_role_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBase) ProtoMessage() {}

func (x *RoleBase) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBase.ProtoReflect.Descriptor instead.
func (*RoleBase) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBase) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleBase) GetRegisterTm() int64 {
	if x != nil {
		return x.RegisterTm
	}
	return 0
}

func (x *RoleBase) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *RoleBase) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RoleBase) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *RoleBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleBase) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 修改角色名称
type RoleAlterName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterName) Reset() {
	*x = RoleAlterName{}
	mi := &file_role_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterName) ProtoMessage() {}

func (x *RoleAlterName) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterName.ProtoReflect.Descriptor instead.
func (*RoleAlterName) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{1}
}

// 修改角色头像
type RoleAlterFace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterFace) Reset() {
	*x = RoleAlterFace{}
	mi := &file_role_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterFace) ProtoMessage() {}

func (x *RoleAlterFace) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterFace.ProtoReflect.Descriptor instead.
func (*RoleAlterFace) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{2}
}

// 修改引导步骤
type RoleAlterStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterStep) Reset() {
	*x = RoleAlterStep{}
	mi := &file_role_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterStep) ProtoMessage() {}

func (x *RoleAlterStep) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterStep.ProtoReflect.Descriptor instead.
func (*RoleAlterStep) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{3}
}

type RoleAlterNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterNameRequest) Reset() {
	*x = RoleAlterNameRequest{}
	mi := &file_role_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterNameRequest) ProtoMessage() {}

func (x *RoleAlterNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterNameRequest.ProtoReflect.Descriptor instead.
func (*RoleAlterNameRequest) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RoleAlterNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleAlterNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterNameResponse) Reset() {
	*x = RoleAlterNameResponse{}
	mi := &file_role_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterNameResponse) ProtoMessage() {}

func (x *RoleAlterNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterNameResponse.ProtoReflect.Descriptor instead.
func (*RoleAlterNameResponse) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RoleAlterNameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RoleAlterFaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarId      int32                  `protobuf:"varint,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`   // 角色头像id
	FrameId       int32                  `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`      //头像框id
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` //自定义头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterFaceRequest) Reset() {
	*x = RoleAlterFaceRequest{}
	mi := &file_role_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterFaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterFaceRequest) ProtoMessage() {}

func (x *RoleAlterFaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterFaceRequest.ProtoReflect.Descriptor instead.
func (*RoleAlterFaceRequest) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RoleAlterFaceRequest) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *RoleAlterFaceRequest) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RoleAlterFaceRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type RoleAlterFaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterFaceResponse) Reset() {
	*x = RoleAlterFaceResponse{}
	mi := &file_role_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterFaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterFaceResponse) ProtoMessage() {}

func (x *RoleAlterFaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterFaceResponse.ProtoReflect.Descriptor instead.
func (*RoleAlterFaceResponse) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RoleAlterFaceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RoleAlterStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterStepRequest) Reset() {
	*x = RoleAlterStepRequest{}
	mi := &file_role_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterStepRequest) ProtoMessage() {}

func (x *RoleAlterStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterStepRequest.ProtoReflect.Descriptor instead.
func (*RoleAlterStepRequest) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RoleAlterStepRequest) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type RoleAlterStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Step          int32                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAlterStepResponse) Reset() {
	*x = RoleAlterStepResponse{}
	mi := &file_role_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAlterStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAlterStepResponse) ProtoMessage() {}

func (x *RoleAlterStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAlterStepResponse.ProtoReflect.Descriptor instead.
func (*RoleAlterStepResponse) Descriptor() ([]byte, []int) {
	return file_role_msg_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RoleAlterStepResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RoleAlterStepResponse) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

var File_role_msg_proto protoreflect.FileDescriptor

const file_role_msg_proto_rawDesc = "" +
	"\n" +
	"\x0erole_msg.proto\x12\brole_msg\"\xc4\x01\n" +
	"\trole_base\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1f\n" +
	"\vregister_tm\x18\x02 \x01(\x03R\n" +
	"registerTm\x12\x1b\n" +
	"\tavatar_id\x18\x04 \x01(\x05R\bavatarId\x12\x19\n" +
	"\bframe_id\x18\x05 \x01(\x05R\aframeId\x12\x12\n" +
	"\x04step\x18\x06 \x01(\x05R\x04step\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\v \x01(\tR\tavatarUrl\"P\n" +
	"\x0frole_alter_name\x1a\x1d\n" +
	"\arequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\x1e\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"\x93\x01\n" +
	"\x0frole_alter_face\x1a`\n" +
	"\arequest\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\x05R\bavatarId\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x05R\aframeId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x1a\x1e\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"d\n" +
	"\x0frole_alter_step\x1a\x1d\n" +
	"\arequest\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x1a2\n" +
	"\bresponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x05R\x04stepB\x1eZ\vwx_game/msg\xaa\x02\x0eNet.Proto.Roleb\x06proto3"

var (
	file_role_msg_proto_rawDescOnce sync.Once
	file_role_msg_proto_rawDescData []byte
)

func file_role_msg_proto_rawDescGZIP() []byte {
	file_role_msg_proto_rawDescOnce.Do(func() {
		file_role_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_msg_proto_rawDesc), len(file_role_msg_proto_rawDesc)))
	})
	return file_role_msg_proto_rawDescData
}

var file_role_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_role_msg_proto_goTypes = []any{
	(*RoleBase)(nil),              // 0: role_msg.role_base
	(*RoleAlterName)(nil),         // 1: role_msg.role_alter_name
	(*RoleAlterFace)(nil),         // 2: role_msg.role_alter_face
	(*RoleAlterStep)(nil),         // 3: role_msg.role_alter_step
	(*RoleAlterNameRequest)(nil),  // 4: role_msg.role_alter_name.request
	(*RoleAlterNameResponse)(nil), // 5: role_msg.role_alter_name.response
	(*RoleAlterFaceRequest)(nil),  // 6: role_msg.role_alter_face.request
	(*RoleAlterFaceResponse)(nil), // 7: role_msg.role_alter_face.response
	(*RoleAlterStepRequest)(nil),  // 8: role_msg.role_alter_step.request
	(*RoleAlterStepResponse)(nil), // 9: role_msg.role_alter_step.response
}
var file_role_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_msg_proto_init() }
func file_role_msg_proto_init() {
	if File_role_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_msg_proto_rawDesc), len(file_role_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_msg_proto_goTypes,
		DependencyIndexes: file_role_msg_proto_depIdxs,
		MessageInfos:      file_role_msg_proto_msgTypes,
	}.Build()
	File_role_msg_proto = out.File
	file_role_msg_proto_goTypes = nil
	file_role_msg_proto_depIdxs = nil
}
