// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: role_server_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改角色名称
type DBRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *RoleBase              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` //等于OpenId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBRole) Reset() {
	*x = DBRole{}
	mi := &file_role_server_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRole) ProtoMessage() {}

func (x *DBRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_server_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRole.ProtoReflect.Descriptor instead.
func (*DBRole) Descriptor() ([]byte, []int) {
	return file_role_server_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DBRole) GetBase() *RoleBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DBRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_role_server_msg_proto protoreflect.FileDescriptor

const file_role_server_msg_proto_rawDesc = "" +
	"\n" +
	"\x15role_server_msg.proto\x1a\x0erole_msg.proto\"I\n" +
	"\x06DBRole\x12&\n" +
	"\x04base\x18\x01 \x01(\v2\x12.role_msg.RoleBaseR\x04base\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userIdB\x1fZ\vwx_game/msg\xaa\x02\x0fNet.Proto.Loginb\x06proto3"

var (
	file_role_server_msg_proto_rawDescOnce sync.Once
	file_role_server_msg_proto_rawDescData []byte
)

func file_role_server_msg_proto_rawDescGZIP() []byte {
	file_role_server_msg_proto_rawDescOnce.Do(func() {
		file_role_server_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_server_msg_proto_rawDesc), len(file_role_server_msg_proto_rawDesc)))
	})
	return file_role_server_msg_proto_rawDescData
}

var file_role_server_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_role_server_msg_proto_goTypes = []any{
	(*DBRole)(nil),   // 0: DBRole
	(*RoleBase)(nil), // 1: role_msg.RoleBase
}
var file_role_server_msg_proto_depIdxs = []int32{
	1, // 0: DBRole.base:type_name -> role_msg.RoleBase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_role_server_msg_proto_init() }
func file_role_server_msg_proto_init() {
	if File_role_server_msg_proto != nil {
		return
	}
	file_role_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_server_msg_proto_rawDesc), len(file_role_server_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_server_msg_proto_goTypes,
		DependencyIndexes: file_role_server_msg_proto_depIdxs,
		MessageInfos:      file_role_server_msg_proto_msgTypes,
	}.Build()
	File_role_server_msg_proto = out.File
	file_role_server_msg_proto_goTypes = nil
	file_role_server_msg_proto_depIdxs = nil
}
