// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: role_server_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改角色名称
type DBRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 角色名字
	AvatarId      int32                  `protobuf:"varint,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`   // 角色头像id
	FrameId       int32                  `protobuf:"varint,4,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`      //头像框id
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` //自定义头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBRole) Reset() {
	*x = DBRole{}
	mi := &file_role_server_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRole) ProtoMessage() {}

func (x *DBRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_server_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRole.ProtoReflect.Descriptor instead.
func (*DBRole) Descriptor() ([]byte, []int) {
	return file_role_server_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DBRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DBRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBRole) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *DBRole) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *DBRole) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_role_server_msg_proto protoreflect.FileDescriptor

const file_role_server_msg_proto_rawDesc = "" +
	"\n" +
	"\x15role_server_msg.proto\"\x8c\x01\n" +
	"\x06DBRole\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\x05R\bavatarId\x12\x19\n" +
	"\bframe_id\x18\x04 \x01(\x05R\aframeId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrlB\x1fZ\vwx_game/msg\xaa\x02\x0fNet.Proto.Loginb\x06proto3"

var (
	file_role_server_msg_proto_rawDescOnce sync.Once
	file_role_server_msg_proto_rawDescData []byte
)

func file_role_server_msg_proto_rawDescGZIP() []byte {
	file_role_server_msg_proto_rawDescOnce.Do(func() {
		file_role_server_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_server_msg_proto_rawDesc), len(file_role_server_msg_proto_rawDesc)))
	})
	return file_role_server_msg_proto_rawDescData
}

var file_role_server_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_role_server_msg_proto_goTypes = []any{
	(*DBRole)(nil), // 0: DBRole
}
var file_role_server_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_server_msg_proto_init() }
func file_role_server_msg_proto_init() {
	if File_role_server_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_server_msg_proto_rawDesc), len(file_role_server_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_server_msg_proto_goTypes,
		DependencyIndexes: file_role_server_msg_proto_depIdxs,
		MessageInfos:      file_role_server_msg_proto_msgTypes,
	}.Build()
	File_role_server_msg_proto = out.File
	file_role_server_msg_proto_goTypes = nil
	file_role_server_msg_proto_depIdxs = nil
}
