// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: watermelon_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个大西瓜信息
type WaterMelonEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	PosX          float32                `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Angle         float32                `protobuf:"fixed32,5,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterMelonEntity) Reset() {
	*x = WaterMelonEntity{}
	mi := &file_watermelon_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterMelonEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterMelonEntity) ProtoMessage() {}

func (x *WaterMelonEntity) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterMelonEntity.ProtoReflect.Descriptor instead.
func (*WaterMelonEntity) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WaterMelonEntity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WaterMelonEntity) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WaterMelonEntity) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *WaterMelonEntity) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *WaterMelonEntity) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

// 西瓜进度快照
type WaterMelonRecordSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Records         []*WaterMelonEntity    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	ProgressScore   int32                  `protobuf:"varint,2,opt,name=progress_score,json=progressScore,proto3" json:"progress_score,omitempty"`                                                                                      // 单局积分
	MapItemUseCount map[int32]int32        `protobuf:"bytes,3,rep,name=map_item_use_count,json=mapItemUseCount,proto3" json:"map_item_use_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 单局使用道具次数 <item_id, count>
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WaterMelonRecordSnapshot) Reset() {
	*x = WaterMelonRecordSnapshot{}
	mi := &file_watermelon_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterMelonRecordSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterMelonRecordSnapshot) ProtoMessage() {}

func (x *WaterMelonRecordSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterMelonRecordSnapshot.ProtoReflect.Descriptor instead.
func (*WaterMelonRecordSnapshot) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WaterMelonRecordSnapshot) GetRecords() []*WaterMelonEntity {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *WaterMelonRecordSnapshot) GetProgressScore() int32 {
	if x != nil {
		return x.ProgressScore
	}
	return 0
}

func (x *WaterMelonRecordSnapshot) GetMapItemUseCount() map[int32]int32 {
	if x != nil {
		return x.MapItemUseCount
	}
	return nil
}

type WaterMelonInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ActivityRepeatedTimes   int32                  `protobuf:"varint,2,opt,name=activity_repeated_times,json=activityRepeatedTimes,proto3" json:"activity_repeated_times,omitempty"`                                                                                      // 重复次数
	Score                   int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`                                                                                                                                                     // 最高积分
	MapActivityItemUseCount map[int32]int32        `protobuf:"bytes,9,rep,name=map_activity_item_use_count,json=mapActivityItemUseCount,proto3" json:"map_activity_item_use_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 活动期间使用道具次数 <item_id, count>
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WaterMelonInfo) Reset() {
	*x = WaterMelonInfo{}
	mi := &file_watermelon_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterMelonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterMelonInfo) ProtoMessage() {}

func (x *WaterMelonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterMelonInfo.ProtoReflect.Descriptor instead.
func (*WaterMelonInfo) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2}
}

func (x *WaterMelonInfo) GetActivityRepeatedTimes() int32 {
	if x != nil {
		return x.ActivityRepeatedTimes
	}
	return 0
}

func (x *WaterMelonInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *WaterMelonInfo) GetMapActivityItemUseCount() map[int32]int32 {
	if x != nil {
		return x.MapActivityItemUseCount
	}
	return nil
}

type WATERMELON_INFO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_INFO) Reset() {
	*x = WATERMELON_INFO{}
	mi := &file_watermelon_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_INFO) ProtoMessage() {}

func (x *WATERMELON_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_INFO.ProtoReflect.Descriptor instead.
func (*WATERMELON_INFO) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3}
}

// 请求游戏开始
type WATERMELON_START struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START) Reset() {
	*x = WATERMELON_START{}
	mi := &file_watermelon_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START) ProtoMessage() {}

func (x *WATERMELON_START) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START.ProtoReflect.Descriptor instead.
func (*WATERMELON_START) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4}
}

// 请求游戏结束
type WATERMELON_END struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END) Reset() {
	*x = WATERMELON_END{}
	mi := &file_watermelon_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END) ProtoMessage() {}

func (x *WATERMELON_END) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END.ProtoReflect.Descriptor instead.
func (*WATERMELON_END) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{5}
}

// 请求后续西瓜
type WATERMELON_NEXT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_NEXT) Reset() {
	*x = WATERMELON_NEXT{}
	mi := &file_watermelon_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_NEXT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_NEXT) ProtoMessage() {}

func (x *WATERMELON_NEXT) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_NEXT.ProtoReflect.Descriptor instead.
func (*WATERMELON_NEXT) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6}
}

// 请求西瓜开始掉落
type WATERMELON_FALL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL) Reset() {
	*x = WATERMELON_FALL{}
	mi := &file_watermelon_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL) ProtoMessage() {}

func (x *WATERMELON_FALL) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7}
}

// 合并信息
type WATER_MELON_MERGE_DETAIL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int32                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"` // id小的合并到id大的
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATER_MELON_MERGE_DETAIL) Reset() {
	*x = WATER_MELON_MERGE_DETAIL{}
	mi := &file_watermelon_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATER_MELON_MERGE_DETAIL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATER_MELON_MERGE_DETAIL) ProtoMessage() {}

func (x *WATER_MELON_MERGE_DETAIL) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATER_MELON_MERGE_DETAIL.ProtoReflect.Descriptor instead.
func (*WATER_MELON_MERGE_DETAIL) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8}
}

func (x *WATER_MELON_MERGE_DETAIL) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *WATER_MELON_MERGE_DETAIL) GetToId() int32 {
	if x != nil {
		return x.ToId
	}
	return 0
}

// 请求西瓜合并
type WATERMELON_MERGE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_MERGE) Reset() {
	*x = WATERMELON_MERGE{}
	mi := &file_watermelon_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_MERGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_MERGE) ProtoMessage() {}

func (x *WATERMELON_MERGE) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_MERGE.ProtoReflect.Descriptor instead.
func (*WATERMELON_MERGE) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{9}
}

// 使用道具
type WATERMELON_USE_ITEM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM) Reset() {
	*x = WATERMELON_USE_ITEM{}
	mi := &file_watermelon_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{10}
}

type WATERMELON_INFO_Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *WaterMelonInfo        `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_INFO_Notify) Reset() {
	*x = WATERMELON_INFO_Notify{}
	mi := &file_watermelon_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_INFO_Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_INFO_Notify) ProtoMessage() {}

func (x *WATERMELON_INFO_Notify) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_INFO_Notify.ProtoReflect.Descriptor instead.
func (*WATERMELON_INFO_Notify) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WATERMELON_INFO_Notify) GetInfo() *WaterMelonInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type WATERMELON_START_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START_Request) Reset() {
	*x = WATERMELON_START_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START_Request) ProtoMessage() {}

func (x *WATERMELON_START_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_START_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 0}
}

type WATERMELON_START_Response struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ErrorCode     uint32                    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Snapshot      *WaterMelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Stamina       int32                     `protobuf:"varint,3,opt,name=stamina,proto3" json:"stamina,omitempty"`                      // 体力
	StaminaTm     int64                     `protobuf:"varint,4,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"` // 体力刷新时间戳秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START_Response) Reset() {
	*x = WATERMELON_START_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START_Response) ProtoMessage() {}

func (x *WATERMELON_START_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_START_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 1}
}

func (x *WATERMELON_START_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_START_Response) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *WATERMELON_START_Response) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WATERMELON_START_Response) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

type WATERMELON_END_Request struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Snapshot      *WaterMelonRecordSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END_Request) Reset() {
	*x = WATERMELON_END_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END_Request) ProtoMessage() {}

func (x *WATERMELON_END_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_END_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WATERMELON_END_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_END_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END_Response) Reset() {
	*x = WATERMELON_END_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END_Response) ProtoMessage() {}

func (x *WATERMELON_END_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_END_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{5, 1}
}

func (x *WATERMELON_END_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type WATERMELON_NEXT_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_NEXT_Request) Reset() {
	*x = WATERMELON_NEXT_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_NEXT_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_NEXT_Request) ProtoMessage() {}

func (x *WATERMELON_NEXT_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_NEXT_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_NEXT_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 0}
}

type WATERMELON_NEXT_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	EntityLst     []*WaterMelonEntity    `protobuf:"bytes,2,rep,name=entity_lst,json=entityLst,proto3" json:"entity_lst,omitempty"`  // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
	Stamina       int32                  `protobuf:"varint,3,opt,name=stamina,proto3" json:"stamina,omitempty"`                      // 体力
	StaminaTm     int64                  `protobuf:"varint,4,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"` // 体力刷新时间戳秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_NEXT_Response) Reset() {
	*x = WATERMELON_NEXT_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_NEXT_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_NEXT_Response) ProtoMessage() {}

func (x *WATERMELON_NEXT_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_NEXT_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_NEXT_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 1}
}

func (x *WATERMELON_NEXT_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_NEXT_Response) GetEntityLst() []*WaterMelonEntity {
	if x != nil {
		return x.EntityLst
	}
	return nil
}

func (x *WATERMELON_NEXT_Response) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WATERMELON_NEXT_Response) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

type WATERMELON_FALL_Request struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	WaterMelonId  int32                     `protobuf:"varint,1,opt,name=water_melon_id,json=waterMelonId,proto3" json:"water_melon_id,omitempty"`
	Snapshot      *WaterMelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL_Request) Reset() {
	*x = WATERMELON_FALL_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL_Request) ProtoMessage() {}

func (x *WATERMELON_FALL_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 0}
}

func (x *WATERMELON_FALL_Request) GetWaterMelonId() int32 {
	if x != nil {
		return x.WaterMelonId
	}
	return 0
}

func (x *WATERMELON_FALL_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_FALL_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Stamina       int32                  `protobuf:"varint,2,opt,name=stamina,proto3" json:"stamina,omitempty"`                      // 体力(返回错误码也保证有值)
	StaminaTm     int64                  `protobuf:"varint,3,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"` // 体力刷新时间戳秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL_Response) Reset() {
	*x = WATERMELON_FALL_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL_Response) ProtoMessage() {}

func (x *WATERMELON_FALL_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 1}
}

func (x *WATERMELON_FALL_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_FALL_Response) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WATERMELON_FALL_Response) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

type WATERMELON_MERGE_Request struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	MergeLst      []*WATER_MELON_MERGE_DETAIL `protobuf:"bytes,1,rep,name=merge_lst,json=mergeLst,proto3" json:"merge_lst,omitempty"` // 合并先后顺序必须有序
	Snapshot      *WaterMelonRecordSnapshot   `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_MERGE_Request) Reset() {
	*x = WATERMELON_MERGE_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_MERGE_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_MERGE_Request) ProtoMessage() {}

func (x *WATERMELON_MERGE_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_MERGE_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_MERGE_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{9, 0}
}

func (x *WATERMELON_MERGE_Request) GetMergeLst() []*WATER_MELON_MERGE_DETAIL {
	if x != nil {
		return x.MergeLst
	}
	return nil
}

func (x *WATERMELON_MERGE_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_MERGE_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_MERGE_Response) Reset() {
	*x = WATERMELON_MERGE_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_MERGE_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_MERGE_Response) ProtoMessage() {}

func (x *WATERMELON_MERGE_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_MERGE_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_MERGE_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{9, 1}
}

func (x *WATERMELON_MERGE_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type WATERMELON_USE_ITEM_Request struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	ItemId          int32                     `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                       // 体力，消除，换位置，升级
	ItemNum         int32                     `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`                                    // 只有体力道具可以有多个
	WaterMelonIdLst []int32                   `protobuf:"varint,3,rep,packed,name=water_melon_id_lst,json=waterMelonIdLst,proto3" json:"water_melon_id_lst,omitempty"` // 操作涉及的西瓜Id列表,没有则不填
	Snapshot        *WaterMelonRecordSnapshot `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                                                  // 使用道具前快照
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM_Request) Reset() {
	*x = WATERMELON_USE_ITEM_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM_Request) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{10, 0}
}

func (x *WATERMELON_USE_ITEM_Request) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Request) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Request) GetWaterMelonIdLst() []int32 {
	if x != nil {
		return x.WaterMelonIdLst
	}
	return nil
}

func (x *WATERMELON_USE_ITEM_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_USE_ITEM_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint32                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemUseCount  int32                  `protobuf:"varint,3,opt,name=item_use_count,json=itemUseCount,proto3" json:"item_use_count,omitempty"`   // 更新map_item_use_count或map_activity_item_use_count
	NextEntityLst []*WaterMelonEntity    `protobuf:"bytes,6,rep,name=next_entity_lst,json=nextEntityLst,proto3" json:"next_entity_lst,omitempty"` // 重新生成后续西瓜,客户端直接覆盖
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM_Response) Reset() {
	*x = WATERMELON_USE_ITEM_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM_Response) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{10, 1}
}

func (x *WATERMELON_USE_ITEM_Response) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Response) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Response) GetItemUseCount() int32 {
	if x != nil {
		return x.ItemUseCount
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Response) GetNextEntityLst() []*WaterMelonEntity {
	if x != nil {
		return x.NextEntityLst
	}
	return nil
}

var File_watermelon_msg_proto protoreflect.FileDescriptor

const file_watermelon_msg_proto_rawDesc = "" +
	"\n" +
	"\x14watermelon_msg.proto\"x\n" +
	"\x10WaterMelonEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x02R\x04posY\x12\x14\n" +
	"\x05angle\x18\x05 \x01(\x02R\x05angle\"\x8f\x02\n" +
	"\x18WaterMelonRecordSnapshot\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.WaterMelonEntityR\arecords\x12%\n" +
	"\x0eprogress_score\x18\x02 \x01(\x05R\rprogressScore\x12[\n" +
	"\x12map_item_use_count\x18\x03 \x03(\v2..WaterMelonRecordSnapshot.MapItemUseCountEntryR\x0fmapItemUseCount\x1aB\n" +
	"\x14MapItemUseCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x96\x02\n" +
	"\x0eWaterMelonInfo\x126\n" +
	"\x17activity_repeated_times\x18\x02 \x01(\x05R\x15activityRepeatedTimes\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12j\n" +
	"\x1bmap_activity_item_use_count\x18\t \x03(\v2,.WaterMelonInfo.MapActivityItemUseCountEntryR\x17mapActivityItemUseCount\x1aJ\n" +
	"\x1cMapActivityItemUseCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"@\n" +
	"\x0fWATERMELON_INFO\x1a-\n" +
	"\x06Notify\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.WaterMelonInfoR\x04info\"\xb9\x01\n" +
	"\x10WATERMELON_START\x1a\t\n" +
	"\aRequest\x1a\x99\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x12\x18\n" +
	"\astamina\x18\x03 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x04 \x01(\x03R\tstaminaTm\"}\n" +
	"\x0eWATERMELON_END\x1a@\n" +
	"\aRequest\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a)\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\"\xb3\x01\n" +
	"\x0fWATERMELON_NEXT\x1a\t\n" +
	"\aRequest\x1a\x94\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\x120\n" +
	"\n" +
	"entity_lst\x18\x02 \x03(\v2\x11.WaterMelonEntityR\tentityLst\x12\x18\n" +
	"\astamina\x18\x03 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x04 \x01(\x03R\tstaminaTm\"\xdd\x01\n" +
	"\x0fWATERMELON_FALL\x1af\n" +
	"\aRequest\x12$\n" +
	"\x0ewater_melon_id\x18\x01 \x01(\x05R\fwaterMelonId\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1ab\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\x12\x18\n" +
	"\astamina\x18\x02 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x03 \x01(\x03R\tstaminaTm\"H\n" +
	"\x18WATER_MELON_MERGE_DETAIL\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x05R\x04toId\"\xb7\x01\n" +
	"\x10WATERMELON_MERGE\x1ax\n" +
	"\aRequest\x126\n" +
	"\tmerge_lst\x18\x01 \x03(\v2\x19.WATER_MELON_MERGE_DETAILR\bmergeLst\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a)\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\"\xdf\x02\n" +
	"\x13WATERMELON_USE_ITEM\x1a\xa1\x01\n" +
	"\aRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\x12+\n" +
	"\x12water_melon_id_lst\x18\x03 \x03(\x05R\x0fwaterMelonIdLst\x125\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a\xa3\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\rR\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12$\n" +
	"\x0eitem_use_count\x18\x03 \x01(\x05R\fitemUseCount\x129\n" +
	"\x0fnext_entity_lst\x18\x06 \x03(\v2\x11.WaterMelonEntityR\rnextEntityLstB$Z\vwx_game/msg\xaa\x02\x14Net.Proto.Watermelonb\x06proto3"

var (
	file_watermelon_msg_proto_rawDescOnce sync.Once
	file_watermelon_msg_proto_rawDescData []byte
)

func file_watermelon_msg_proto_rawDescGZIP() []byte {
	file_watermelon_msg_proto_rawDescOnce.Do(func() {
		file_watermelon_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)))
	})
	return file_watermelon_msg_proto_rawDescData
}

var file_watermelon_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_watermelon_msg_proto_goTypes = []any{
	(*WaterMelonEntity)(nil),             // 0: WaterMelonEntity
	(*WaterMelonRecordSnapshot)(nil),     // 1: WaterMelonRecordSnapshot
	(*WaterMelonInfo)(nil),               // 2: WaterMelonInfo
	(*WATERMELON_INFO)(nil),              // 3: WATERMELON_INFO
	(*WATERMELON_START)(nil),             // 4: WATERMELON_START
	(*WATERMELON_END)(nil),               // 5: WATERMELON_END
	(*WATERMELON_NEXT)(nil),              // 6: WATERMELON_NEXT
	(*WATERMELON_FALL)(nil),              // 7: WATERMELON_FALL
	(*WATER_MELON_MERGE_DETAIL)(nil),     // 8: WATER_MELON_MERGE_DETAIL
	(*WATERMELON_MERGE)(nil),             // 9: WATERMELON_MERGE
	(*WATERMELON_USE_ITEM)(nil),          // 10: WATERMELON_USE_ITEM
	nil,                                  // 11: WaterMelonRecordSnapshot.MapItemUseCountEntry
	nil,                                  // 12: WaterMelonInfo.MapActivityItemUseCountEntry
	(*WATERMELON_INFO_Notify)(nil),       // 13: WATERMELON_INFO.Notify
	(*WATERMELON_START_Request)(nil),     // 14: WATERMELON_START.Request
	(*WATERMELON_START_Response)(nil),    // 15: WATERMELON_START.Response
	(*WATERMELON_END_Request)(nil),       // 16: WATERMELON_END.Request
	(*WATERMELON_END_Response)(nil),      // 17: WATERMELON_END.Response
	(*WATERMELON_NEXT_Request)(nil),      // 18: WATERMELON_NEXT.Request
	(*WATERMELON_NEXT_Response)(nil),     // 19: WATERMELON_NEXT.Response
	(*WATERMELON_FALL_Request)(nil),      // 20: WATERMELON_FALL.Request
	(*WATERMELON_FALL_Response)(nil),     // 21: WATERMELON_FALL.Response
	(*WATERMELON_MERGE_Request)(nil),     // 22: WATERMELON_MERGE.Request
	(*WATERMELON_MERGE_Response)(nil),    // 23: WATERMELON_MERGE.Response
	(*WATERMELON_USE_ITEM_Request)(nil),  // 24: WATERMELON_USE_ITEM.Request
	(*WATERMELON_USE_ITEM_Response)(nil), // 25: WATERMELON_USE_ITEM.Response
}
var file_watermelon_msg_proto_depIdxs = []int32{
	0,  // 0: WaterMelonRecordSnapshot.records:type_name -> WaterMelonEntity
	11, // 1: WaterMelonRecordSnapshot.map_item_use_count:type_name -> WaterMelonRecordSnapshot.MapItemUseCountEntry
	12, // 2: WaterMelonInfo.map_activity_item_use_count:type_name -> WaterMelonInfo.MapActivityItemUseCountEntry
	2,  // 3: WATERMELON_INFO.Notify.info:type_name -> WaterMelonInfo
	1,  // 4: WATERMELON_START.Response.snapshot:type_name -> WaterMelonRecordSnapshot
	1,  // 5: WATERMELON_END.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	0,  // 6: WATERMELON_NEXT.Response.entity_lst:type_name -> WaterMelonEntity
	1,  // 7: WATERMELON_FALL.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	8,  // 8: WATERMELON_MERGE.Request.merge_lst:type_name -> WATER_MELON_MERGE_DETAIL
	1,  // 9: WATERMELON_MERGE.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	1,  // 10: WATERMELON_USE_ITEM.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	0,  // 11: WATERMELON_USE_ITEM.Response.next_entity_lst:type_name -> WaterMelonEntity
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_watermelon_msg_proto_init() }
func file_watermelon_msg_proto_init() {
	if File_watermelon_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watermelon_msg_proto_goTypes,
		DependencyIndexes: file_watermelon_msg_proto_depIdxs,
		MessageInfos:      file_watermelon_msg_proto_msgTypes,
	}.Build()
	File_watermelon_msg_proto = out.File
	file_watermelon_msg_proto_goTypes = nil
	file_watermelon_msg_proto_depIdxs = nil
}
