// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: watermelon_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个大西瓜信息
type WatermelonEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	PosX          float32                `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Angle         float32                `protobuf:"fixed32,5,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonEntity) Reset() {
	*x = WatermelonEntity{}
	mi := &file_watermelon_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonEntity) ProtoMessage() {}

func (x *WatermelonEntity) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonEntity.ProtoReflect.Descriptor instead.
func (*WatermelonEntity) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WatermelonEntity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WatermelonEntity) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WatermelonEntity) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *WatermelonEntity) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *WatermelonEntity) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

// 西瓜进度快照
type WatermelonRecordSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*WatermelonEntity    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonRecordSnapshot) Reset() {
	*x = WatermelonRecordSnapshot{}
	mi := &file_watermelon_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonRecordSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonRecordSnapshot) ProtoMessage() {}

func (x *WatermelonRecordSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonRecordSnapshot.ProtoReflect.Descriptor instead.
func (*WatermelonRecordSnapshot) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WatermelonRecordSnapshot) GetRecords() []*WatermelonEntity {
	if x != nil {
		return x.Records
	}
	return nil
}

// 请求游戏开始
type WatermelonStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonStart) Reset() {
	*x = WatermelonStart{}
	mi := &file_watermelon_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonStart) ProtoMessage() {}

func (x *WatermelonStart) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonStart.ProtoReflect.Descriptor instead.
func (*WatermelonStart) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2}
}

// 请求游戏结束
type WatermelonEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonEnd) Reset() {
	*x = WatermelonEnd{}
	mi := &file_watermelon_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonEnd) ProtoMessage() {}

func (x *WatermelonEnd) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonEnd.ProtoReflect.Descriptor instead.
func (*WatermelonEnd) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3}
}

// 请求西瓜开始掉落
type WatermelonFall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonFall) Reset() {
	*x = WatermelonFall{}
	mi := &file_watermelon_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonFall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonFall) ProtoMessage() {}

func (x *WatermelonFall) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonFall.ProtoReflect.Descriptor instead.
func (*WatermelonFall) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4}
}

// 合并信息
type WatermelonMergeDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int32                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"` // id小的合并到id大的
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonMergeDetail) Reset() {
	*x = WatermelonMergeDetail{}
	mi := &file_watermelon_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonMergeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonMergeDetail) ProtoMessage() {}

func (x *WatermelonMergeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonMergeDetail.ProtoReflect.Descriptor instead.
func (*WatermelonMergeDetail) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{5}
}

func (x *WatermelonMergeDetail) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *WatermelonMergeDetail) GetToId() int32 {
	if x != nil {
		return x.ToId
	}
	return 0
}

// 请求西瓜同步-包含合并
type WatermelonSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonSync) Reset() {
	*x = WatermelonSync{}
	mi := &file_watermelon_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonSync) ProtoMessage() {}

func (x *WatermelonSync) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonSync.ProtoReflect.Descriptor instead.
func (*WatermelonSync) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6}
}

// 使用道具
type WatermelonUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonUseItem) Reset() {
	*x = WatermelonUseItem{}
	mi := &file_watermelon_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonUseItem) ProtoMessage() {}

func (x *WatermelonUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonUseItem.ProtoReflect.Descriptor instead.
func (*WatermelonUseItem) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7}
}

// 添加道具
type WatermelonAddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonAddItem) Reset() {
	*x = WatermelonAddItem{}
	mi := &file_watermelon_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonAddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonAddItem) ProtoMessage() {}

func (x *WatermelonAddItem) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonAddItem.ProtoReflect.Descriptor instead.
func (*WatermelonAddItem) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8}
}

type WatermelonStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonStartRequest) Reset() {
	*x = WatermelonStartRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonStartRequest) ProtoMessage() {}

func (x *WatermelonStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonStartRequest.ProtoReflect.Descriptor instead.
func (*WatermelonStartRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2, 0}
}

type WatermelonStartResponse struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ErrorCode      int32                     `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Snapshot       *WatermelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Stamina        int32                     `protobuf:"varint,3,opt,name=stamina,proto3" json:"stamina,omitempty"`                                                                                                            // 体力
	StaminaTm      int64                     `protobuf:"varint,4,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"`                                                                                       // 体力刷新时间戳秒
	EntityLst      []*WatermelonEntity       `protobuf:"bytes,5,rep,name=entity_lst,json=entityLst,proto3" json:"entity_lst,omitempty"`                                                                                        // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
	HistoryScore   int32                     `protobuf:"varint,6,opt,name=history_score,json=historyScore,proto3" json:"history_score,omitempty"`                                                                              // 历史最高积分
	Score          int32                     `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`                                                                                                                // 当前积分
	MapItemCount   map[int32]int32           `protobuf:"bytes,8,rep,name=map_item_count,json=mapItemCount,proto3" json:"map_item_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //  剩余可用道具次数 <item_id, count>
	RemainAddCount int32                     `protobuf:"varint,9,opt,name=remain_add_count,json=remainAddCount,proto3" json:"remain_add_count,omitempty"`                                                                      //剩余可添加物品次数
	FallCnt        int32                     `protobuf:"varint,10,opt,name=fall_cnt,json=fallCnt,proto3" json:"fall_cnt,omitempty"`                                                                                            //本局请求掉落数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatermelonStartResponse) Reset() {
	*x = WatermelonStartResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonStartResponse) ProtoMessage() {}

func (x *WatermelonStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonStartResponse.ProtoReflect.Descriptor instead.
func (*WatermelonStartResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2, 1}
}

func (x *WatermelonStartResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WatermelonStartResponse) GetSnapshot() *WatermelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *WatermelonStartResponse) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WatermelonStartResponse) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

func (x *WatermelonStartResponse) GetEntityLst() []*WatermelonEntity {
	if x != nil {
		return x.EntityLst
	}
	return nil
}

func (x *WatermelonStartResponse) GetHistoryScore() int32 {
	if x != nil {
		return x.HistoryScore
	}
	return 0
}

func (x *WatermelonStartResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *WatermelonStartResponse) GetMapItemCount() map[int32]int32 {
	if x != nil {
		return x.MapItemCount
	}
	return nil
}

func (x *WatermelonStartResponse) GetRemainAddCount() int32 {
	if x != nil {
		return x.RemainAddCount
	}
	return 0
}

func (x *WatermelonStartResponse) GetFallCnt() int32 {
	if x != nil {
		return x.FallCnt
	}
	return 0
}

type WatermelonEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonEndRequest) Reset() {
	*x = WatermelonEndRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonEndRequest) ProtoMessage() {}

func (x *WatermelonEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonEndRequest.ProtoReflect.Descriptor instead.
func (*WatermelonEndRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3, 0}
}

type WatermelonEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonEndResponse) Reset() {
	*x = WatermelonEndResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonEndResponse) ProtoMessage() {}

func (x *WatermelonEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonEndResponse.ProtoReflect.Descriptor instead.
func (*WatermelonEndResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3, 1}
}

func (x *WatermelonEndResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type WatermelonFallRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	WatermelonId  int32                     `protobuf:"varint,1,opt,name=watermelon_id,json=watermelonId,proto3" json:"watermelon_id,omitempty"`
	Snapshot      *WatermelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonFallRequest) Reset() {
	*x = WatermelonFallRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonFallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonFallRequest) ProtoMessage() {}

func (x *WatermelonFallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonFallRequest.ProtoReflect.Descriptor instead.
func (*WatermelonFallRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WatermelonFallRequest) GetWatermelonId() int32 {
	if x != nil {
		return x.WatermelonId
	}
	return 0
}

func (x *WatermelonFallRequest) GetSnapshot() *WatermelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatermelonFallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Stamina       int32                  `protobuf:"varint,2,opt,name=stamina,proto3" json:"stamina,omitempty"`                      // 体力(返回错误码也保证有值)
	StaminaTm     int64                  `protobuf:"varint,3,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"` // 体力刷新时间戳秒
	EntityLst     []*WatermelonEntity    `protobuf:"bytes,4,rep,name=entity_lst,json=entityLst,proto3" json:"entity_lst,omitempty"`  // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
	FallCnt       int32                  `protobuf:"varint,5,opt,name=fall_cnt,json=fallCnt,proto3" json:"fall_cnt,omitempty"`       //本局请求掉落数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonFallResponse) Reset() {
	*x = WatermelonFallResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonFallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonFallResponse) ProtoMessage() {}

func (x *WatermelonFallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonFallResponse.ProtoReflect.Descriptor instead.
func (*WatermelonFallResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 1}
}

func (x *WatermelonFallResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WatermelonFallResponse) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WatermelonFallResponse) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

func (x *WatermelonFallResponse) GetEntityLst() []*WatermelonEntity {
	if x != nil {
		return x.EntityLst
	}
	return nil
}

func (x *WatermelonFallResponse) GetFallCnt() int32 {
	if x != nil {
		return x.FallCnt
	}
	return 0
}

type WatermelonSyncRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	MergeLst      []*WatermelonMergeDetail  `protobuf:"bytes,1,rep,name=merge_lst,json=mergeLst,proto3" json:"merge_lst,omitempty"` // 合并先后顺序必须有序
	Snapshot      *WatermelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonSyncRequest) Reset() {
	*x = WatermelonSyncRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonSyncRequest) ProtoMessage() {}

func (x *WatermelonSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonSyncRequest.ProtoReflect.Descriptor instead.
func (*WatermelonSyncRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 0}
}

func (x *WatermelonSyncRequest) GetMergeLst() []*WatermelonMergeDetail {
	if x != nil {
		return x.MergeLst
	}
	return nil
}

func (x *WatermelonSyncRequest) GetSnapshot() *WatermelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatermelonSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 当前积分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonSyncResponse) Reset() {
	*x = WatermelonSyncResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonSyncResponse) ProtoMessage() {}

func (x *WatermelonSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonSyncResponse.ProtoReflect.Descriptor instead.
func (*WatermelonSyncResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 1}
}

func (x *WatermelonSyncResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WatermelonSyncResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type WatermelonUseItemRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	ItemId          int32                     `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                     // 体力，消除，换位置，升级
	ItemNum         int32                     `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`                                  // 只有体力道具可以有多个
	WatermelonIdLst []int32                   `protobuf:"varint,3,rep,packed,name=watermelon_id_lst,json=watermelonIdLst,proto3" json:"watermelon_id_lst,omitempty"` // 操作涉及的西瓜Id列表,没有则不填
	Snapshot        *WatermelonRecordSnapshot `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                                                // 使用道具后的快照
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatermelonUseItemRequest) Reset() {
	*x = WatermelonUseItemRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonUseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonUseItemRequest) ProtoMessage() {}

func (x *WatermelonUseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonUseItemRequest.ProtoReflect.Descriptor instead.
func (*WatermelonUseItemRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 0}
}

func (x *WatermelonUseItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WatermelonUseItemRequest) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *WatermelonUseItemRequest) GetWatermelonIdLst() []int32 {
	if x != nil {
		return x.WatermelonIdLst
	}
	return nil
}

func (x *WatermelonUseItemRequest) GetSnapshot() *WatermelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatermelonUseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"` // 剩余可用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonUseItemResponse) Reset() {
	*x = WatermelonUseItemResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonUseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonUseItemResponse) ProtoMessage() {}

func (x *WatermelonUseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonUseItemResponse.ProtoReflect.Descriptor instead.
func (*WatermelonUseItemResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 1}
}

func (x *WatermelonUseItemResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WatermelonUseItemResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WatermelonUseItemResponse) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type WatermelonAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermelonAddItemRequest) Reset() {
	*x = WatermelonAddItemRequest{}
	mi := &file_watermelon_msg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonAddItemRequest) ProtoMessage() {}

func (x *WatermelonAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonAddItemRequest.ProtoReflect.Descriptor instead.
func (*WatermelonAddItemRequest) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8, 0}
}

func (x *WatermelonAddItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WatermelonAddItemRequest) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type WatermelonAddItemResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode      int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ItemId         int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum        int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`                        // 剩余可用数量
	RemainAddCount int32                  `protobuf:"varint,4,opt,name=remain_add_count,json=remainAddCount,proto3" json:"remain_add_count,omitempty"` //剩余可添加物品次数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatermelonAddItemResponse) Reset() {
	*x = WatermelonAddItemResponse{}
	mi := &file_watermelon_msg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermelonAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermelonAddItemResponse) ProtoMessage() {}

func (x *WatermelonAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermelonAddItemResponse.ProtoReflect.Descriptor instead.
func (*WatermelonAddItemResponse) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8, 1}
}

func (x *WatermelonAddItemResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WatermelonAddItemResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WatermelonAddItemResponse) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *WatermelonAddItemResponse) GetRemainAddCount() int32 {
	if x != nil {
		return x.RemainAddCount
	}
	return 0
}

var File_watermelon_msg_proto protoreflect.FileDescriptor

const file_watermelon_msg_proto_rawDesc = "" +
	"\n" +
	"\x14watermelon_msg.proto\"y\n" +
	"\x11watermelon_entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x02R\x04posY\x12\x14\n" +
	"\x05angle\x18\x05 \x01(\x02R\x05angle\"J\n" +
	"\x1awatermelon_record_snapshot\x12,\n" +
	"\arecords\x18\x01 \x03(\v2\x12.watermelon_entityR\arecords\"\x83\x04\n" +
	"\x10watermelon_start\x1a\t\n" +
	"\arequest\x1a\xe3\x03\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1b.watermelon_record_snapshotR\bsnapshot\x12\x18\n" +
	"\astamina\x18\x03 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x04 \x01(\x03R\tstaminaTm\x121\n" +
	"\n" +
	"entity_lst\x18\x05 \x03(\v2\x12.watermelon_entityR\tentityLst\x12#\n" +
	"\rhistory_score\x18\x06 \x01(\x05R\fhistoryScore\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12R\n" +
	"\x0emap_item_count\x18\b \x03(\v2,.watermelon_start.response.MapItemCountEntryR\fmapItemCount\x12(\n" +
	"\x10remain_add_count\x18\t \x01(\x05R\x0eremainAddCount\x12\x19\n" +
	"\bfall_cnt\x18\n" +
	" \x01(\x05R\afallCnt\x1a?\n" +
	"\x11MapItemCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"F\n" +
	"\x0ewatermelon_end\x1a\t\n" +
	"\arequest\x1a)\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\"\xad\x02\n" +
	"\x0fwatermelon_fall\x1ag\n" +
	"\arequest\x12#\n" +
	"\rwatermelon_id\x18\x01 \x01(\x05R\fwatermelonId\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1b.watermelon_record_snapshotR\bsnapshot\x1a\xb0\x01\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x18\n" +
	"\astamina\x18\x02 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x03 \x01(\x03R\tstaminaTm\x121\n" +
	"\n" +
	"entity_lst\x18\x04 \x03(\v2\x12.watermelon_entityR\tentityLst\x12\x19\n" +
	"\bfall_cnt\x18\x05 \x01(\x05R\afallCnt\"G\n" +
	"\x17watermelon_merge_detail\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x05R\x04toId\"\xcd\x01\n" +
	"\x0fwatermelon_sync\x1ay\n" +
	"\arequest\x125\n" +
	"\tmerge_lst\x18\x01 \x03(\v2\x18.watermelon_merge_detailR\bmergeLst\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1b.watermelon_record_snapshotR\bsnapshot\x1a?\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\x99\x02\n" +
	"\x13watermelon_use_item\x1a\xa2\x01\n" +
	"\arequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\x12*\n" +
	"\x11watermelon_id_lst\x18\x03 \x03(\x05R\x0fwatermelonIdLst\x127\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x1b.watermelon_record_snapshotR\bsnapshot\x1a]\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"\xde\x01\n" +
	"\x13watermelon_add_item\x1a=\n" +
	"\arequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\x1a\x87\x01\n" +
	"\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\x12(\n" +
	"\x10remain_add_count\x18\x04 \x01(\x05R\x0eremainAddCountB$Z\vwx_game/msg\xaa\x02\x14Net.Proto.Watermelonb\x06proto3"

var (
	file_watermelon_msg_proto_rawDescOnce sync.Once
	file_watermelon_msg_proto_rawDescData []byte
)

func file_watermelon_msg_proto_rawDescGZIP() []byte {
	file_watermelon_msg_proto_rawDescOnce.Do(func() {
		file_watermelon_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)))
	})
	return file_watermelon_msg_proto_rawDescData
}

var file_watermelon_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_watermelon_msg_proto_goTypes = []any{
	(*WatermelonEntity)(nil),          // 0: watermelon_entity
	(*WatermelonRecordSnapshot)(nil),  // 1: watermelon_record_snapshot
	(*WatermelonStart)(nil),           // 2: watermelon_start
	(*WatermelonEnd)(nil),             // 3: watermelon_end
	(*WatermelonFall)(nil),            // 4: watermelon_fall
	(*WatermelonMergeDetail)(nil),     // 5: watermelon_merge_detail
	(*WatermelonSync)(nil),            // 6: watermelon_sync
	(*WatermelonUseItem)(nil),         // 7: watermelon_use_item
	(*WatermelonAddItem)(nil),         // 8: watermelon_add_item
	(*WatermelonStartRequest)(nil),    // 9: watermelon_start.request
	(*WatermelonStartResponse)(nil),   // 10: watermelon_start.response
	nil,                               // 11: watermelon_start.response.MapItemCountEntry
	(*WatermelonEndRequest)(nil),      // 12: watermelon_end.request
	(*WatermelonEndResponse)(nil),     // 13: watermelon_end.response
	(*WatermelonFallRequest)(nil),     // 14: watermelon_fall.request
	(*WatermelonFallResponse)(nil),    // 15: watermelon_fall.response
	(*WatermelonSyncRequest)(nil),     // 16: watermelon_sync.request
	(*WatermelonSyncResponse)(nil),    // 17: watermelon_sync.response
	(*WatermelonUseItemRequest)(nil),  // 18: watermelon_use_item.request
	(*WatermelonUseItemResponse)(nil), // 19: watermelon_use_item.response
	(*WatermelonAddItemRequest)(nil),  // 20: watermelon_add_item.request
	(*WatermelonAddItemResponse)(nil), // 21: watermelon_add_item.response
}
var file_watermelon_msg_proto_depIdxs = []int32{
	0,  // 0: watermelon_record_snapshot.records:type_name -> watermelon_entity
	1,  // 1: watermelon_start.response.snapshot:type_name -> watermelon_record_snapshot
	0,  // 2: watermelon_start.response.entity_lst:type_name -> watermelon_entity
	11, // 3: watermelon_start.response.map_item_count:type_name -> watermelon_start.response.MapItemCountEntry
	1,  // 4: watermelon_fall.request.snapshot:type_name -> watermelon_record_snapshot
	0,  // 5: watermelon_fall.response.entity_lst:type_name -> watermelon_entity
	5,  // 6: watermelon_sync.request.merge_lst:type_name -> watermelon_merge_detail
	1,  // 7: watermelon_sync.request.snapshot:type_name -> watermelon_record_snapshot
	1,  // 8: watermelon_use_item.request.snapshot:type_name -> watermelon_record_snapshot
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_watermelon_msg_proto_init() }
func file_watermelon_msg_proto_init() {
	if File_watermelon_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watermelon_msg_proto_goTypes,
		DependencyIndexes: file_watermelon_msg_proto_depIdxs,
		MessageInfos:      file_watermelon_msg_proto_msgTypes,
	}.Build()
	File_watermelon_msg_proto = out.File
	file_watermelon_msg_proto_goTypes = nil
	file_watermelon_msg_proto_depIdxs = nil
}
