// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: watermelon_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个大西瓜信息
type WaterMelonEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	PosX          float32                `protobuf:"fixed32,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Angle         float32                `protobuf:"fixed32,5,opt,name=angle,proto3" json:"angle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterMelonEntity) Reset() {
	*x = WaterMelonEntity{}
	mi := &file_watermelon_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterMelonEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterMelonEntity) ProtoMessage() {}

func (x *WaterMelonEntity) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterMelonEntity.ProtoReflect.Descriptor instead.
func (*WaterMelonEntity) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WaterMelonEntity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WaterMelonEntity) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *WaterMelonEntity) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *WaterMelonEntity) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *WaterMelonEntity) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

// 西瓜进度快照
type WaterMelonRecordSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*WaterMelonEntity    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterMelonRecordSnapshot) Reset() {
	*x = WaterMelonRecordSnapshot{}
	mi := &file_watermelon_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterMelonRecordSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterMelonRecordSnapshot) ProtoMessage() {}

func (x *WaterMelonRecordSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterMelonRecordSnapshot.ProtoReflect.Descriptor instead.
func (*WaterMelonRecordSnapshot) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{1}
}

func (x *WaterMelonRecordSnapshot) GetRecords() []*WaterMelonEntity {
	if x != nil {
		return x.Records
	}
	return nil
}

// 请求游戏开始
type WATERMELON_START struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START) Reset() {
	*x = WATERMELON_START{}
	mi := &file_watermelon_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START) ProtoMessage() {}

func (x *WATERMELON_START) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START.ProtoReflect.Descriptor instead.
func (*WATERMELON_START) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2}
}

// 请求游戏结束
type WATERMELON_END struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END) Reset() {
	*x = WATERMELON_END{}
	mi := &file_watermelon_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END) ProtoMessage() {}

func (x *WATERMELON_END) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END.ProtoReflect.Descriptor instead.
func (*WATERMELON_END) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3}
}

// 请求西瓜开始掉落
type WATERMELON_FALL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL) Reset() {
	*x = WATERMELON_FALL{}
	mi := &file_watermelon_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL) ProtoMessage() {}

func (x *WATERMELON_FALL) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4}
}

// 合并信息
type WATER_MELON_MERGE_DETAIL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          int32                  `protobuf:"varint,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"` // id小的合并到id大的
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATER_MELON_MERGE_DETAIL) Reset() {
	*x = WATER_MELON_MERGE_DETAIL{}
	mi := &file_watermelon_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATER_MELON_MERGE_DETAIL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATER_MELON_MERGE_DETAIL) ProtoMessage() {}

func (x *WATER_MELON_MERGE_DETAIL) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATER_MELON_MERGE_DETAIL.ProtoReflect.Descriptor instead.
func (*WATER_MELON_MERGE_DETAIL) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{5}
}

func (x *WATER_MELON_MERGE_DETAIL) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *WATER_MELON_MERGE_DETAIL) GetToId() int32 {
	if x != nil {
		return x.ToId
	}
	return 0
}

// 请求西瓜同步-包含合并
type WATERMELON_SYNC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_SYNC) Reset() {
	*x = WATERMELON_SYNC{}
	mi := &file_watermelon_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_SYNC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_SYNC) ProtoMessage() {}

func (x *WATERMELON_SYNC) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_SYNC.ProtoReflect.Descriptor instead.
func (*WATERMELON_SYNC) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6}
}

// 使用道具
type WATERMELON_USE_ITEM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM) Reset() {
	*x = WATERMELON_USE_ITEM{}
	mi := &file_watermelon_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7}
}

// 添加道具
type WATERMELON_ADD_ITEM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_ADD_ITEM) Reset() {
	*x = WATERMELON_ADD_ITEM{}
	mi := &file_watermelon_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_ADD_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_ADD_ITEM) ProtoMessage() {}

func (x *WATERMELON_ADD_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_ADD_ITEM.ProtoReflect.Descriptor instead.
func (*WATERMELON_ADD_ITEM) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8}
}

type WATERMELON_START_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START_Request) Reset() {
	*x = WATERMELON_START_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START_Request) ProtoMessage() {}

func (x *WATERMELON_START_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_START_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2, 0}
}

type WATERMELON_START_Response struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ErrorCode     int32                     `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Snapshot      *WaterMelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Stamina       int32                     `protobuf:"varint,3,opt,name=stamina,proto3" json:"stamina,omitempty"`                                                                                                            // 体力
	StaminaTm     int64                     `protobuf:"varint,4,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"`                                                                                       // 体力刷新时间戳秒
	EntityLst     []*WaterMelonEntity       `protobuf:"bytes,5,rep,name=entity_lst,json=entityLst,proto3" json:"entity_lst,omitempty"`                                                                                        // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
	HistoryScore  int32                     `protobuf:"varint,6,opt,name=history_score,json=historyScore,proto3" json:"history_score,omitempty"`                                                                              // 历史最高积分
	Score         int32                     `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`                                                                                                                // 当前积分
	MapItemCount  map[int32]int32           `protobuf:"bytes,8,rep,name=map_item_count,json=mapItemCount,proto3" json:"map_item_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //  剩余可用道具次数 <item_id, count>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_START_Response) Reset() {
	*x = WATERMELON_START_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_START_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_START_Response) ProtoMessage() {}

func (x *WATERMELON_START_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_START_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_START_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{2, 1}
}

func (x *WATERMELON_START_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_START_Response) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *WATERMELON_START_Response) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WATERMELON_START_Response) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

func (x *WATERMELON_START_Response) GetEntityLst() []*WaterMelonEntity {
	if x != nil {
		return x.EntityLst
	}
	return nil
}

func (x *WATERMELON_START_Response) GetHistoryScore() int32 {
	if x != nil {
		return x.HistoryScore
	}
	return 0
}

func (x *WATERMELON_START_Response) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *WATERMELON_START_Response) GetMapItemCount() map[int32]int32 {
	if x != nil {
		return x.MapItemCount
	}
	return nil
}

type WATERMELON_END_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END_Request) Reset() {
	*x = WATERMELON_END_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END_Request) ProtoMessage() {}

func (x *WATERMELON_END_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_END_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3, 0}
}

type WATERMELON_END_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_END_Response) Reset() {
	*x = WATERMELON_END_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_END_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_END_Response) ProtoMessage() {}

func (x *WATERMELON_END_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_END_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_END_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{3, 1}
}

func (x *WATERMELON_END_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type WATERMELON_FALL_Request struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	WaterMelonId  int32                     `protobuf:"varint,1,opt,name=water_melon_id,json=waterMelonId,proto3" json:"water_melon_id,omitempty"`
	Snapshot      *WaterMelonRecordSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL_Request) Reset() {
	*x = WATERMELON_FALL_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL_Request) ProtoMessage() {}

func (x *WATERMELON_FALL_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WATERMELON_FALL_Request) GetWaterMelonId() int32 {
	if x != nil {
		return x.WaterMelonId
	}
	return 0
}

func (x *WATERMELON_FALL_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_FALL_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Stamina       int32                  `protobuf:"varint,2,opt,name=stamina,proto3" json:"stamina,omitempty"`                      // 体力(返回错误码也保证有值)
	StaminaTm     int64                  `protobuf:"varint,3,opt,name=stamina_tm,json=staminaTm,proto3" json:"stamina_tm,omitempty"` // 体力刷新时间戳秒
	EntityLst     []*WaterMelonEntity    `protobuf:"bytes,4,rep,name=entity_lst,json=entityLst,proto3" json:"entity_lst,omitempty"`  // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_FALL_Response) Reset() {
	*x = WATERMELON_FALL_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_FALL_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_FALL_Response) ProtoMessage() {}

func (x *WATERMELON_FALL_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_FALL_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_FALL_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{4, 1}
}

func (x *WATERMELON_FALL_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_FALL_Response) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *WATERMELON_FALL_Response) GetStaminaTm() int64 {
	if x != nil {
		return x.StaminaTm
	}
	return 0
}

func (x *WATERMELON_FALL_Response) GetEntityLst() []*WaterMelonEntity {
	if x != nil {
		return x.EntityLst
	}
	return nil
}

type WATERMELON_SYNC_Request struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	MergeLst      []*WATER_MELON_MERGE_DETAIL `protobuf:"bytes,1,rep,name=merge_lst,json=mergeLst,proto3" json:"merge_lst,omitempty"` // 合并先后顺序必须有序
	Snapshot      *WaterMelonRecordSnapshot   `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_SYNC_Request) Reset() {
	*x = WATERMELON_SYNC_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_SYNC_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_SYNC_Request) ProtoMessage() {}

func (x *WATERMELON_SYNC_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_SYNC_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_SYNC_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 0}
}

func (x *WATERMELON_SYNC_Request) GetMergeLst() []*WATER_MELON_MERGE_DETAIL {
	if x != nil {
		return x.MergeLst
	}
	return nil
}

func (x *WATERMELON_SYNC_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_SYNC_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 当前积分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_SYNC_Response) Reset() {
	*x = WATERMELON_SYNC_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_SYNC_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_SYNC_Response) ProtoMessage() {}

func (x *WATERMELON_SYNC_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_SYNC_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_SYNC_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{6, 1}
}

func (x *WATERMELON_SYNC_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_SYNC_Response) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type WATERMELON_USE_ITEM_Request struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	ItemId          int32                     `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                       // 体力，消除，换位置，升级
	ItemNum         int32                     `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`                                    // 只有体力道具可以有多个
	WaterMelonIdLst []int32                   `protobuf:"varint,3,rep,packed,name=water_melon_id_lst,json=waterMelonIdLst,proto3" json:"water_melon_id_lst,omitempty"` // 操作涉及的西瓜Id列表,没有则不填
	Snapshot        *WaterMelonRecordSnapshot `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                                                  // 使用道具后的快照
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM_Request) Reset() {
	*x = WATERMELON_USE_ITEM_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM_Request) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 0}
}

func (x *WATERMELON_USE_ITEM_Request) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Request) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Request) GetWaterMelonIdLst() []int32 {
	if x != nil {
		return x.WaterMelonIdLst
	}
	return nil
}

func (x *WATERMELON_USE_ITEM_Request) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WATERMELON_USE_ITEM_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"` // 剩余可用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_USE_ITEM_Response) Reset() {
	*x = WATERMELON_USE_ITEM_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_USE_ITEM_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_USE_ITEM_Response) ProtoMessage() {}

func (x *WATERMELON_USE_ITEM_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_USE_ITEM_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_USE_ITEM_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{7, 1}
}

func (x *WATERMELON_USE_ITEM_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Response) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_USE_ITEM_Response) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type WATERMELON_ADD_ITEM_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_ADD_ITEM_Request) Reset() {
	*x = WATERMELON_ADD_ITEM_Request{}
	mi := &file_watermelon_msg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_ADD_ITEM_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_ADD_ITEM_Request) ProtoMessage() {}

func (x *WATERMELON_ADD_ITEM_Request) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_ADD_ITEM_Request.ProtoReflect.Descriptor instead.
func (*WATERMELON_ADD_ITEM_Request) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8, 0}
}

func (x *WATERMELON_ADD_ITEM_Request) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_ADD_ITEM_Request) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type WATERMELON_ADD_ITEM_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"` // 剩余可用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WATERMELON_ADD_ITEM_Response) Reset() {
	*x = WATERMELON_ADD_ITEM_Response{}
	mi := &file_watermelon_msg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WATERMELON_ADD_ITEM_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WATERMELON_ADD_ITEM_Response) ProtoMessage() {}

func (x *WATERMELON_ADD_ITEM_Response) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_msg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WATERMELON_ADD_ITEM_Response.ProtoReflect.Descriptor instead.
func (*WATERMELON_ADD_ITEM_Response) Descriptor() ([]byte, []int) {
	return file_watermelon_msg_proto_rawDescGZIP(), []int{8, 1}
}

func (x *WATERMELON_ADD_ITEM_Response) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WATERMELON_ADD_ITEM_Response) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *WATERMELON_ADD_ITEM_Response) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

var File_watermelon_msg_proto protoreflect.FileDescriptor

const file_watermelon_msg_proto_rawDesc = "" +
	"\n" +
	"\x14watermelon_msg.proto\"x\n" +
	"\x10WaterMelonEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x02R\x04posY\x12\x14\n" +
	"\x05angle\x18\x05 \x01(\x02R\x05angle\"G\n" +
	"\x18WaterMelonRecordSnapshot\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.WaterMelonEntityR\arecords\"\xbb\x03\n" +
	"\x10WATERMELON_START\x1a\t\n" +
	"\aRequest\x1a\x9b\x03\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x12\x18\n" +
	"\astamina\x18\x03 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x04 \x01(\x03R\tstaminaTm\x120\n" +
	"\n" +
	"entity_lst\x18\x05 \x03(\v2\x11.WaterMelonEntityR\tentityLst\x12#\n" +
	"\rhistory_score\x18\x06 \x01(\x05R\fhistoryScore\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12R\n" +
	"\x0emap_item_count\x18\b \x03(\v2,.WATERMELON_START.Response.MapItemCountEntryR\fmapItemCount\x1a?\n" +
	"\x11MapItemCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"F\n" +
	"\x0eWATERMELON_END\x1a\t\n" +
	"\aRequest\x1a)\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\"\x90\x02\n" +
	"\x0fWATERMELON_FALL\x1af\n" +
	"\aRequest\x12$\n" +
	"\x0ewater_melon_id\x18\x01 \x01(\x05R\fwaterMelonId\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a\x94\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x18\n" +
	"\astamina\x18\x02 \x01(\x05R\astamina\x12\x1d\n" +
	"\n" +
	"stamina_tm\x18\x03 \x01(\x03R\tstaminaTm\x120\n" +
	"\n" +
	"entity_lst\x18\x04 \x03(\v2\x11.WaterMelonEntityR\tentityLst\"H\n" +
	"\x18WATER_MELON_MERGE_DETAIL\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\x05R\x04toId\"\xcc\x01\n" +
	"\x0fWATERMELON_SYNC\x1ax\n" +
	"\aRequest\x126\n" +
	"\tmerge_lst\x18\x01 \x03(\v2\x19.WATER_MELON_MERGE_DETAILR\bmergeLst\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a?\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\x98\x02\n" +
	"\x13WATERMELON_USE_ITEM\x1a\xa1\x01\n" +
	"\aRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\x12+\n" +
	"\x12water_melon_id_lst\x18\x03 \x03(\x05R\x0fwaterMelonIdLst\x125\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x1a]\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"\xb3\x01\n" +
	"\x13WATERMELON_ADD_ITEM\x1a=\n" +
	"\aRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x05R\aitemNum\x1a]\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNumB$Z\vwx_game/msg\xaa\x02\x14Net.Proto.Watermelonb\x06proto3"

var (
	file_watermelon_msg_proto_rawDescOnce sync.Once
	file_watermelon_msg_proto_rawDescData []byte
)

func file_watermelon_msg_proto_rawDescGZIP() []byte {
	file_watermelon_msg_proto_rawDescOnce.Do(func() {
		file_watermelon_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)))
	})
	return file_watermelon_msg_proto_rawDescData
}

var file_watermelon_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_watermelon_msg_proto_goTypes = []any{
	(*WaterMelonEntity)(nil),             // 0: WaterMelonEntity
	(*WaterMelonRecordSnapshot)(nil),     // 1: WaterMelonRecordSnapshot
	(*WATERMELON_START)(nil),             // 2: WATERMELON_START
	(*WATERMELON_END)(nil),               // 3: WATERMELON_END
	(*WATERMELON_FALL)(nil),              // 4: WATERMELON_FALL
	(*WATER_MELON_MERGE_DETAIL)(nil),     // 5: WATER_MELON_MERGE_DETAIL
	(*WATERMELON_SYNC)(nil),              // 6: WATERMELON_SYNC
	(*WATERMELON_USE_ITEM)(nil),          // 7: WATERMELON_USE_ITEM
	(*WATERMELON_ADD_ITEM)(nil),          // 8: WATERMELON_ADD_ITEM
	(*WATERMELON_START_Request)(nil),     // 9: WATERMELON_START.Request
	(*WATERMELON_START_Response)(nil),    // 10: WATERMELON_START.Response
	nil,                                  // 11: WATERMELON_START.Response.MapItemCountEntry
	(*WATERMELON_END_Request)(nil),       // 12: WATERMELON_END.Request
	(*WATERMELON_END_Response)(nil),      // 13: WATERMELON_END.Response
	(*WATERMELON_FALL_Request)(nil),      // 14: WATERMELON_FALL.Request
	(*WATERMELON_FALL_Response)(nil),     // 15: WATERMELON_FALL.Response
	(*WATERMELON_SYNC_Request)(nil),      // 16: WATERMELON_SYNC.Request
	(*WATERMELON_SYNC_Response)(nil),     // 17: WATERMELON_SYNC.Response
	(*WATERMELON_USE_ITEM_Request)(nil),  // 18: WATERMELON_USE_ITEM.Request
	(*WATERMELON_USE_ITEM_Response)(nil), // 19: WATERMELON_USE_ITEM.Response
	(*WATERMELON_ADD_ITEM_Request)(nil),  // 20: WATERMELON_ADD_ITEM.Request
	(*WATERMELON_ADD_ITEM_Response)(nil), // 21: WATERMELON_ADD_ITEM.Response
}
var file_watermelon_msg_proto_depIdxs = []int32{
	0,  // 0: WaterMelonRecordSnapshot.records:type_name -> WaterMelonEntity
	1,  // 1: WATERMELON_START.Response.snapshot:type_name -> WaterMelonRecordSnapshot
	0,  // 2: WATERMELON_START.Response.entity_lst:type_name -> WaterMelonEntity
	11, // 3: WATERMELON_START.Response.map_item_count:type_name -> WATERMELON_START.Response.MapItemCountEntry
	1,  // 4: WATERMELON_FALL.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	0,  // 5: WATERMELON_FALL.Response.entity_lst:type_name -> WaterMelonEntity
	5,  // 6: WATERMELON_SYNC.Request.merge_lst:type_name -> WATER_MELON_MERGE_DETAIL
	1,  // 7: WATERMELON_SYNC.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	1,  // 8: WATERMELON_USE_ITEM.Request.snapshot:type_name -> WaterMelonRecordSnapshot
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_watermelon_msg_proto_init() }
func file_watermelon_msg_proto_init() {
	if File_watermelon_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watermelon_msg_proto_rawDesc), len(file_watermelon_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watermelon_msg_proto_goTypes,
		DependencyIndexes: file_watermelon_msg_proto_depIdxs,
		MessageInfos:      file_watermelon_msg_proto_msgTypes,
	}.Build()
	File_watermelon_msg_proto = out.File
	file_watermelon_msg_proto_goTypes = nil
	file_watermelon_msg_proto_depIdxs = nil
}
