// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: watermelon_server_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBWaterMelon struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	RoleId               int64                     `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AutoIncrId           int32                     `protobuf:"varint,2,opt,name=auto_incr_id,json=autoIncrId,proto3" json:"auto_incr_id,omitempty"`
	Snapshot             *WaterMelonRecordSnapshot `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	NextLst              []*WaterMelonEntity       `protobuf:"bytes,4,rep,name=next_lst,json=nextLst,proto3" json:"next_lst,omitempty"`
	InsideGameMaxLv      int32                     `protobuf:"varint,5,opt,name=inside_game_max_lv,json=insideGameMaxLv,proto3" json:"inside_game_max_lv,omitempty"`                                                                                            // 局内最大等级
	HistoryScore         int32                     `protobuf:"varint,6,opt,name=history_score,json=historyScore,proto3" json:"history_score,omitempty"`                                                                                                         // 历史最高积分
	Score                int32                     `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`                                                                                                                                           // 当前积分
	InsideRemainAddCount int32                     `protobuf:"varint,8,opt,name=inside_remain_add_count,json=insideRemainAddCount,proto3" json:"inside_remain_add_count,omitempty"`                                                                             //局内剩余可添加物品次数
	MapMergeRecord       map[int32]int32           `protobuf:"bytes,15,rep,name=map_merge_record,json=mapMergeRecord,proto3" json:"map_merge_record,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                     // 合成记录 <等级，次数>	整个活动的
	MapMergeInsideRecord map[int32]int32           `protobuf:"bytes,16,rep,name=map_merge_inside_record,json=mapMergeInsideRecord,proto3" json:"map_merge_inside_record,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 合成记录 <等级，次数>	局内的最大值
	MapInsideItemCount   map[int32]int32           `protobuf:"bytes,17,rep,name=map_inside_item_count,json=mapInsideItemCount,proto3" json:"map_inside_item_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // 单局剩余可用道具次数 <item_id, count>
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DBWaterMelon) Reset() {
	*x = DBWaterMelon{}
	mi := &file_watermelon_server_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBWaterMelon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBWaterMelon) ProtoMessage() {}

func (x *DBWaterMelon) ProtoReflect() protoreflect.Message {
	mi := &file_watermelon_server_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBWaterMelon.ProtoReflect.Descriptor instead.
func (*DBWaterMelon) Descriptor() ([]byte, []int) {
	return file_watermelon_server_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DBWaterMelon) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DBWaterMelon) GetAutoIncrId() int32 {
	if x != nil {
		return x.AutoIncrId
	}
	return 0
}

func (x *DBWaterMelon) GetSnapshot() *WaterMelonRecordSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *DBWaterMelon) GetNextLst() []*WaterMelonEntity {
	if x != nil {
		return x.NextLst
	}
	return nil
}

func (x *DBWaterMelon) GetInsideGameMaxLv() int32 {
	if x != nil {
		return x.InsideGameMaxLv
	}
	return 0
}

func (x *DBWaterMelon) GetHistoryScore() int32 {
	if x != nil {
		return x.HistoryScore
	}
	return 0
}

func (x *DBWaterMelon) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DBWaterMelon) GetInsideRemainAddCount() int32 {
	if x != nil {
		return x.InsideRemainAddCount
	}
	return 0
}

func (x *DBWaterMelon) GetMapMergeRecord() map[int32]int32 {
	if x != nil {
		return x.MapMergeRecord
	}
	return nil
}

func (x *DBWaterMelon) GetMapMergeInsideRecord() map[int32]int32 {
	if x != nil {
		return x.MapMergeInsideRecord
	}
	return nil
}

func (x *DBWaterMelon) GetMapInsideItemCount() map[int32]int32 {
	if x != nil {
		return x.MapInsideItemCount
	}
	return nil
}

var File_watermelon_server_msg_proto protoreflect.FileDescriptor

const file_watermelon_server_msg_proto_rawDesc = "" +
	"\n" +
	"\x1bwatermelon_server_msg.proto\x1a\x14watermelon_msg.proto\"\xa7\x06\n" +
	"\fDBWaterMelon\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12 \n" +
	"\fauto_incr_id\x18\x02 \x01(\x05R\n" +
	"autoIncrId\x125\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x19.WaterMelonRecordSnapshotR\bsnapshot\x12,\n" +
	"\bnext_lst\x18\x04 \x03(\v2\x11.WaterMelonEntityR\anextLst\x12+\n" +
	"\x12inside_game_max_lv\x18\x05 \x01(\x05R\x0finsideGameMaxLv\x12#\n" +
	"\rhistory_score\x18\x06 \x01(\x05R\fhistoryScore\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x125\n" +
	"\x17inside_remain_add_count\x18\b \x01(\x05R\x14insideRemainAddCount\x12K\n" +
	"\x10map_merge_record\x18\x0f \x03(\v2!.DBWaterMelon.MapMergeRecordEntryR\x0emapMergeRecord\x12^\n" +
	"\x17map_merge_inside_record\x18\x10 \x03(\v2'.DBWaterMelon.MapMergeInsideRecordEntryR\x14mapMergeInsideRecord\x12X\n" +
	"\x15map_inside_item_count\x18\x11 \x03(\v2%.DBWaterMelon.MapInsideItemCountEntryR\x12mapInsideItemCount\x1aA\n" +
	"\x13MapMergeRecordEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aG\n" +
	"\x19MapMergeInsideRecordEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aE\n" +
	"\x17MapInsideItemCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\rZ\vwx_game/msgb\x06proto3"

var (
	file_watermelon_server_msg_proto_rawDescOnce sync.Once
	file_watermelon_server_msg_proto_rawDescData []byte
)

func file_watermelon_server_msg_proto_rawDescGZIP() []byte {
	file_watermelon_server_msg_proto_rawDescOnce.Do(func() {
		file_watermelon_server_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watermelon_server_msg_proto_rawDesc), len(file_watermelon_server_msg_proto_rawDesc)))
	})
	return file_watermelon_server_msg_proto_rawDescData
}

var file_watermelon_server_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_watermelon_server_msg_proto_goTypes = []any{
	(*DBWaterMelon)(nil),             // 0: DBWaterMelon
	nil,                              // 1: DBWaterMelon.MapMergeRecordEntry
	nil,                              // 2: DBWaterMelon.MapMergeInsideRecordEntry
	nil,                              // 3: DBWaterMelon.MapInsideItemCountEntry
	(*WaterMelonRecordSnapshot)(nil), // 4: WaterMelonRecordSnapshot
	(*WaterMelonEntity)(nil),         // 5: WaterMelonEntity
}
var file_watermelon_server_msg_proto_depIdxs = []int32{
	4, // 0: DBWaterMelon.snapshot:type_name -> WaterMelonRecordSnapshot
	5, // 1: DBWaterMelon.next_lst:type_name -> WaterMelonEntity
	1, // 2: DBWaterMelon.map_merge_record:type_name -> DBWaterMelon.MapMergeRecordEntry
	2, // 3: DBWaterMelon.map_merge_inside_record:type_name -> DBWaterMelon.MapMergeInsideRecordEntry
	3, // 4: DBWaterMelon.map_inside_item_count:type_name -> DBWaterMelon.MapInsideItemCountEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_watermelon_server_msg_proto_init() }
func file_watermelon_server_msg_proto_init() {
	if File_watermelon_server_msg_proto != nil {
		return
	}
	file_watermelon_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watermelon_server_msg_proto_rawDesc), len(file_watermelon_server_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watermelon_server_msg_proto_goTypes,
		DependencyIndexes: file_watermelon_server_msg_proto_depIdxs,
		MessageInfos:      file_watermelon_server_msg_proto_msgTypes,
	}.Build()
	File_watermelon_server_msg_proto = out.File
	file_watermelon_server_msg_proto_goTypes = nil
	file_watermelon_server_msg_proto_depIdxs = nil
}
