
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type AvatarTbPlayerAvatar struct {
    _dataMap map[int32]*AvatarPlayerAvatar
    _dataList []*AvatarPlayerAvatar
}

func NewAvatarTbPlayerAvatar(_buf []map[string]interface{}) (*AvatarTbPlayerAvatar, error) {
    _dataList := make([]*AvatarPlayerAvatar, 0, len(_buf))
    dataMap := make(map[int32]*AvatarPlayerAvatar)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAvatarPlayerAvatar(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.EAvatar] = _v
        }
    }
    return &AvatarTbPlayerAvatar{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *AvatarTbPlayerAvatar) GetDataMap() map[int32]*AvatarPlayerAvatar {
    return table._dataMap
}

func (table *AvatarTbPlayerAvatar) GetDataList() []*AvatarPlayerAvatar {
    return table._dataList
}

func (table *AvatarTbPlayerAvatar) Get(key int32) *AvatarPlayerAvatar {
    return table._dataMap[key]
}


