
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type AvatarPlayerFrame struct {
    EFrame int32
    Quality int32
}

const TypeId_AvatarPlayerFrame = -1982880297

func (*AvatarPlayerFrame) GetTypeId() int32 {
    return -1982880297
}

func NewAvatarPlayerFrame(_buf map[string]interface{}) (_v *AvatarPlayerFrame, err error) {
    _v = &AvatarPlayerFrame{}
    { var _ok_ bool; var __json_EFrame__ interface{}; if __json_EFrame__, _ok_ = _buf["EFrame"]; !_ok_ || __json_EFrame__ == nil { err = errors.New("EFrame error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_EFrame__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EFrame = __x__ }}
    { var _ok_ bool; var __json_Quality__ interface{}; if __json_Quality__, _ok_ = _buf["Quality"]; !_ok_ || __json_Quality__ == nil { err = errors.New("Quality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Quality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Quality = __x__ }}
    return
}

