
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type AvatarPlayerAvatar struct {
    EAvatar int32
}

const TypeId_AvatarPlayerAvatar = -1479192017

func (*AvatarPlayerAvatar) GetTypeId() int32 {
    return -1479192017
}

func NewAvatarPlayerAvatar(_buf map[string]interface{}) (_v *AvatarPlayerAvatar, err error) {
    _v = &AvatarPlayerAvatar{}
    { var _ok_ bool; var __json_EAvatar__ interface{}; if __json_EAvatar__, _ok_ = _buf["EAvatar"]; !_ok_ || __json_EAvatar__ == nil { err = errors.New("EAvatar error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_EAvatar__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EAvatar = __x__ }}
    return
}

