
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type AvatarTbPlayerFrame struct {
    _dataMap map[int32]*AvatarPlayerFrame
    _dataList []*AvatarPlayerFrame
}

func NewAvatarTbPlayerFrame(_buf []map[string]interface{}) (*AvatarTbPlayerFrame, error) {
    _dataList := make([]*AvatarPlayerFrame, 0, len(_buf))
    dataMap := make(map[int32]*AvatarPlayerFrame)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAvatarPlayerFrame(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.EFrame] = _v
        }
    }
    return &AvatarTbPlayerFrame{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *AvatarTbPlayerFrame) GetDataMap() map[int32]*AvatarPlayerFrame {
    return table._dataMap
}

func (table *AvatarTbPlayerFrame) GetDataList() []*AvatarPlayerFrame {
    return table._dataList
}

func (table *AvatarTbPlayerFrame) Get(key int32) *AvatarPlayerFrame {
    return table._dataMap[key]
}


