
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    EAvatar_Avatar_None = 0;
    EAvatar_Avatar_10001 = 10001;
    EAvatar_Avatar_10002 = 10002;
    EAvatar_Avatar_10003 = 10003;
    EAvatar_Avatar_10004 = 10004;
    EAvatar_Avatar_10005 = 10005;
    EAvatar_Avatar_10006 = 10006;
    EAvatar_Avatar_10007 = 10007;
    EAvatar_Avatar_10008 = 10008;
    EAvatar_Avatar_10009 = 10009;
)

