
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    EErrorCode_None = 0;
    /**
     * 内部错误
     */
    EErrorCode_Internal = 10001;
    /**
     * 无效消息
     */
    EErrorCode_InvalidMsg = 10002;
    /**
     * 需要认证
     */
    EErrorCode_AuthRequired = 10003;
    /**
     * 无效token
     */
    EErrorCode_InvalidToken = 10004;
    /**
     * 认证失败
     */
    EErrorCode_AuthFailed = 10005;
    /**
     * token过期
     */
    EErrorCode_TokenExpired = 10006;
    /**
     * 顶号被踢
     */
    EErrorCode_KickRepeatedLogin = 10007;
    /**
     * 合成大西瓜礼包购买达到上限
     */
    EErrorCode_Activity_WaterMelon_BuyNumLimit = 20001;
    /**
     * 合成大西瓜当前奖励无法领取
     */
    EErrorCode_Activity_WaterMelon_Condition = 20002;
    /**
     * 合成大西瓜参数错误
     */
    EErrorCode_Activity_WaterMelon_Parameter = 20003;
    /**
     * 合成大西瓜已购买
     */
    EErrorCode_Activity_WaterMelon_Purchased = 20004;
    /**
     * 合成大西瓜无可领取的奖励
     */
    EErrorCode_Activity_WaterMelon_NotRewardClaim = 20005;
    /**
     * 合成大西瓜体力不足
     */
    EErrorCode_Activity_WaterMelon_StaminaNotEnough = 20006;
    /**
     * 合成大西瓜道具使用数量限制
     */
    EErrorCode_Activity_WaterMelon_UseItemCountLimit = 20007;
    /**
     * 合成大西瓜配置表错误
     */
    EErrorCode_Activity_WaterMelon_Cfg = 20008;
    /**
     * 合成大西瓜内部逻辑错误
     */
    EErrorCode_Activity_WaterMelon_Logic = 20009;
    /**
     * 合成大西瓜添加物品数量不足
     */
    EErrorCode_Activity_WaterMelon_ItemNotEnough = 20010;
    /**
     * 不可添加道具
     */
    EErrorCode_Activity_WaterMelon_ItemCantAdd = 20011;
)

