
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    EFrame_Frame_10001 = 10001;
    EFrame_Frame_10002 = 10002;
    EFrame_Frame_10003 = 10003;
    EFrame_Frame_10004 = 10004;
    EFrame_Frame_10005 = 10005;
    EFrame_Frame_10006 = 10006;
    EFrame_Frame_10007 = 10007;
    EFrame_Frame_10008 = 10008;
    EFrame_Frame_10009 = 10009;
    EFrame_Frame_10010 = 10010;
)

