
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 钻石
     */
    EItem_Diamond = 10001;
    /**
     * 金币
     */
    EItem_Gold = 10002;
    /**
     * 大西瓜消除
     */
    EItem_WatermelonErase = 10003;
    /**
     * 大西瓜换位
     */
    EItem_WatermelonSwap = 10004;
    /**
     * 大西瓜升级
     */
    EItem_WatermelonUpgrade = 10005;
)

