
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * English
     */
    ELanguage_en = 1;
    /**
     * 简体中文
     */
    ELanguage_zh_CN = 2;
    /**
     * 繁體中文
     */
    ELanguage_zh_TW = 3;
    /**
     * Deutsch
     */
    ELanguage_de = 4;
    /**
     * Fran&#231;ais
     */
    ELanguage_fr = 5;
    /**
     * Русский
     */
    ELanguage_ru = 6;
    /**
     * Espa&#241;ol
     */
    ELanguage_es = 7;
    /**
     * Tiếng Việt
     */
    ELanguage_vi = 8;
    /**
     * ไทย
     */
    ELanguage_th = 9;
    /**
     * 日本語
     */
    ELanguage_ja = 10;
    /**
     * 한국어
     */
    ELanguage_ko = 11;
    /**
     * Bahasa Indonesia
     */
    ELanguage_id = 12;
    /**
     * Portugu&#234;s
     */
    ELanguage_pt = 13;
    /**
     * T&#252;rk&#231;e
     */
    ELanguage_tr = 14;
    /**
     * Italiano
     */
    ELanguage_it = 15;
)

