
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 剧情对话枚举
 */
const (
    /**
     * 大西瓜玩法对话
     */
    EPlot_Watermelon_1 = 1;
    /**
     * 新手对话1
     */
    EPlot_Novice_1 = 2;
)

