
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 红
     */
    EQuality_SS = 1;
    /**
     * 橙
     */
    EQuality_S = 2;
    /**
     * 紫
     */
    EQuality_A = 3;
    /**
     * 蓝
     */
    EQuality_B = 4;
    /**
     * 绿
     */
    EQuality_C = 5;
    /**
     * 白
     */
    EQuality_D = 6;
)

