
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 排行榜枚举
 */
const (
    /**
     * 本服大西瓜活动
     */
    ERank_Watermelon = 1;
    /**
     * 本服玩家战力
     */
    ERank_RolePower = 2;
    /**
     * 本服肉鸽关卡
     */
    ERank_RogueLevel = 3;
    /**
     * 本服玩家英雄战力
     */
    ERank_HeroPower = 4;
)

