
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 针对什么对象排行
 */
const (
    /**
     * 玩家
     */
    ERankObject_Role = 1;
    /**
     * 联盟
     */
    ERankObject_League = 2;
    /**
     * 联盟个人
     */
    ERankObject_LeagueRole = 3;
    /**
     * 玩家英雄
     */
    ERankObject_RoleHero = 4;
)

