
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ItemItem struct {
    EItem int32
    Quality int32
}

const TypeId_ItemItem = 2107285806

func (*ItemItem) GetTypeId() int32 {
    return 2107285806
}

func NewItemItem(_buf map[string]interface{}) (_v *ItemItem, err error) {
    _v = &ItemItem{}
    { var _ok_ bool; var __json_EItem__ interface{}; if __json_EItem__, _ok_ = _buf["EItem"]; !_ok_ || __json_EItem__ == nil { err = errors.New("EItem error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_EItem__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.EItem = __x__ }}
    { var _ok_ bool; var __json_Quality__ interface{}; if __json_Quality__, _ok_ = _buf["Quality"]; !_ok_ || __json_Quality__ == nil { err = errors.New("Quality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Quality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Quality = __x__ }}
    return
}

