
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type RankTbRank struct {
    _dataMap map[int32]*RankRank
    _dataList []*RankRank
}

func NewRankTbRank(_buf []map[string]interface{}) (*RankTbRank, error) {
    _dataList := make([]*RankRank, 0, len(_buf))
    dataMap := make(map[int32]*RankRank)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRankRank(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.ERank] = _v
        }
    }
    return &RankTbRank{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *RankTbRank) GetDataMap() map[int32]*RankRank {
    return table._dataMap
}

func (table *RankTbRank) GetDataList() []*RankRank {
    return table._dataList
}

func (table *RankTbRank) Get(key int32) *RankRank {
    return table._dataMap[key]
}


