
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type RankRank struct {
    ERank int32
    ERankObject int32
    LimitNum int32
}

const TypeId_RankRank = -687970098

func (*RankRank) GetTypeId() int32 {
    return -687970098
}

func NewRankRank(_buf map[string]interface{}) (_v *RankRank, err error) {
    _v = &RankRank{}
    { var _ok_ bool; var __json_ERank__ interface{}; if __json_ERank__, _ok_ = _buf["ERank"]; !_ok_ || __json_ERank__ == nil { err = errors.New("ERank error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ERank__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ERank = __x__ }}
    { var _ok_ bool; var __json_ERankObject__ interface{}; if __json_ERankObject__, _ok_ = _buf["ERankObject"]; !_ok_ || __json_ERankObject__ == nil { err = errors.New("ERankObject error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_ERankObject__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ERankObject = __x__ }}
    { var _ok_ bool; var __json_LimitNum__ interface{}; if __json_LimitNum__, _ok_ = _buf["LimitNum"]; !_ok_ || __json_LimitNum__ == nil { err = errors.New("LimitNum error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_LimitNum__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.LimitNum = __x__ }}
    return
}

