
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type WatermelonTbWaterMelonLevel struct {
    _dataMap map[int32]*WatermelonWaterMelonLevel
    _dataList []*WatermelonWaterMelonLevel
}

func NewWatermelonTbWaterMelonLevel(_buf []map[string]interface{}) (*WatermelonTbWaterMelonLevel, error) {
    _dataList := make([]*WatermelonWaterMelonLevel, 0, len(_buf))
    dataMap := make(map[int32]*WatermelonWaterMelonLevel)

    for _, _ele_ := range _buf {
        if _v, err2 := NewWatermelonWaterMelonLevel(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &WatermelonTbWaterMelonLevel{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *WatermelonTbWaterMelonLevel) GetDataMap() map[int32]*WatermelonWaterMelonLevel {
    return table._dataMap
}

func (table *WatermelonTbWaterMelonLevel) GetDataList() []*WatermelonWaterMelonLevel {
    return table._dataList
}

func (table *WatermelonTbWaterMelonLevel) Get(key int32) *WatermelonWaterMelonLevel {
    return table._dataMap[key]
}


