
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type WatermelonWaterMelonLevel struct {
    Id int32
    Point int32
    Weight int32
    UseItemLvUp int32
}

const TypeId_WatermelonWaterMelonLevel = 1163543286

func (*WatermelonWaterMelonLevel) GetTypeId() int32 {
    return 1163543286
}

func NewWatermelonWaterMelonLevel(_buf map[string]interface{}) (_v *WatermelonWaterMelonLevel, err error) {
    _v = &WatermelonWaterMelonLevel{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_Point__ interface{}; if __json_Point__, _ok_ = _buf["Point"]; !_ok_ || __json_Point__ == nil { err = errors.New("Point error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Point__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Point = __x__ }}
    { var _ok_ bool; var __json_Weight__ interface{}; if __json_Weight__, _ok_ = _buf["Weight"]; !_ok_ || __json_Weight__ == nil { err = errors.New("Weight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_Weight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Weight = __x__ }}
    { var _ok_ bool; var __json_UseItemLvUp__ interface{}; if __json_UseItemLvUp__, _ok_ = _buf["UseItemLvUp"]; !_ok_ || __json_UseItemLvUp__ == nil { err = errors.New("UseItemLvUp error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_UseItemLvUp__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UseItemLvUp = __x__ }}
    return
}

