
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type WatermelonWaterMelonConfig struct {
    Id int32
    InitFruit []int32
    NextMaxCnt int32
}

const TypeId_WatermelonWaterMelonConfig = 1461438992

func (*WatermelonWaterMelonConfig) GetTypeId() int32 {
    return 1461438992
}

func NewWatermelonWaterMelonConfig(_buf map[string]interface{}) (_v *WatermelonWaterMelonConfig, err error) {
    _v = &WatermelonWaterMelonConfig{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_initFruit__ interface{}; if __json_initFruit__, _ok_ = _buf["initFruit"]; !_ok_ || __json_initFruit__ == nil { err = errors.New("initFruit error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_initFruit__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.InitFruit = __x__ }}
    { var _ok_ bool; var __json_nextMaxCnt__ interface{}; if __json_nextMaxCnt__, _ok_ = _buf["nextMaxCnt"]; !_ok_ || __json_nextMaxCnt__ == nil { err = errors.New("nextMaxCnt error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_nextMaxCnt__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.NextMaxCnt = __x__ }}
    return
}

