
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type WatermelonTbWaterMelonConfig struct {
    _dataMap map[int32]*WatermelonWaterMelonConfig
    _dataList []*WatermelonWaterMelonConfig
}

func NewWatermelonTbWaterMelonConfig(_buf []map[string]interface{}) (*WatermelonTbWaterMelonConfig, error) {
    _dataList := make([]*WatermelonWaterMelonConfig, 0, len(_buf))
    dataMap := make(map[int32]*WatermelonWaterMelonConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewWatermelonWaterMelonConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &WatermelonTbWaterMelonConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *WatermelonTbWaterMelonConfig) GetDataMap() map[int32]*WatermelonWaterMelonConfig {
    return table._dataMap
}

func (table *WatermelonTbWaterMelonConfig) GetDataList() []*WatermelonWaterMelonConfig {
    return table._dataList
}

func (table *WatermelonTbWaterMelonConfig) Get(key int32) *WatermelonWaterMelonConfig {
    return table._dataMap[key]
}


