syntax = "proto3";

option csharp_namespace = "Net.Proto.Errors";
option go_package = "wx_game/msg";

// 错误码枚举
enum ErrorCode {
  E_ErrorCode_None = 0;           // 成功（默认值，0 表示成功）
  
  // 通用错误码 (10000-11000)
  E_ErrorCode_Internal = 10001;      // 内部错误
  E_ErrorCode_InvalidMsg = 10002;     // 无效消息
  E_ErrorCode_AuthRequired = 10003;       // 需要认证
  E_ErrorCode_InvalidToken = 10004;       // 无效 token
  E_ErrorCode_AuthFailed = 10005;         // 认证失败
  E_ErrorCode_TokenExpired = 10006;       // Token 过期

  //[活动]合成大西瓜[20000, 20100]
  E_ErrorCode_Activity_WaterMelon_BuyNumLimit = 20001;	// [活动]合成大西瓜礼包购买达到上限
  E_ErrorCode_Activity_WaterMelon_Condition = 20002;		// [活动]合成大西瓜条件错误
  E_ErrorCode_Activity_WaterMelon_Parameter = 20003;		// [活动]合成大西瓜请求参数错误
  E_ErrorCode_Activity_WaterMelon_Purchased = 20004;		// [活动]合成大西瓜已购买
  E_ErrorCode_Activity_WaterMelon_NotRewardClaim = 20005;// [活动]合成大西瓜无可领取的奖励
  E_ErrorCode_Activity_WaterMelon_StaminaNotEnough = 20006;// [活动]合成大西瓜体力不足
  E_ErrorCode_Activity_WaterMelon_UseItemCountLimit = 20007;// [活动]合成大西瓜道具使用数量限制
  E_ErrorCode_Activity_WaterMelon_Cfg = 20008; // [活动]合成大西瓜配置表错误
  E_ErrorCode_Activity_WaterMelon_Logic = 20009; // [活动]合成大西瓜内部逻辑错误
}

message MSG_ERROR_CODE
{
  int32 error_code = 1;
}

