syntax = "proto3";
 
option csharp_namespace = "Net.Proto.Login";
option go_package = "wx_game/msg";

import "role_msg.proto";

//登入验证
message login_auth {
    message request{
        string token = 1;                   // JWT token
    }
    message response{
        int32 code = 1;                    // 错误码（第一个字段固定）
        string status = 2;                 // 认证状态，通常为 "authenticated"
        role_msg.role_base role = 3;         //角色信息
    }
}

message ping {
    message request{
        // 空消息
    }
    message response{
        int32 code = 1;                    // 错误码（第一个字段固定）
    }
}

//踢人包
message kick{
    message notify{
        int32 code = 1;
    }
}

//玩家bug反馈
message bug_feedback{
    message request{
        string msg = 1;
    }
    message response{
        int32 code = 1;
    }
}