syntax = "proto3";
package role_msg;

option csharp_namespace = "Net.Proto.Role";
option go_package = "wx_game/msg";

//角色基础信息
message role_base {
    int64 role_id = 1;
    int64 register_tm = 2; //角色注册时间戳
    int32 avatar_id = 4;		// 角色头像id
    int32 frame_id = 5; 		//头像框id
    int32 step = 6; //引导步骤

    string name = 10;        // 角色名字
    string avatar_url = 11;		//自定义头像
}

//修改角色名称
message role_alter_name {
    message request{
        string name = 1;
    }
    message response{
        int32 code = 1;
    }
}

//修改角色头像
message role_alter_face {
    message request{
        int32 avatar_id = 1;		// 角色头像id
        int32 frame_id = 2; 		//头像框id
        string avatar_url = 3;		//自定义头像
    }
    message response{
        int32 code = 1;
    }
}

//修改引导步骤
message role_alter_step {
    message request{
        int32 step = 1;
    }
    message response{
        int32 code = 1;
        int32 step = 2;
    }
}