syntax = "proto3";

option go_package = "wx_game/msg";

import "watermelon_msg.proto";

message db_watermelon{
    int64 role_id = 1;
    int32 auto_incr_id = 2;
    watermelon_record_snapshot snapshot = 3;
    repeated watermelon_entity next_lst = 4;
    int32 inside_game_max_lv = 5;				// 局内最大等级
    int32 history_score = 6;                       		// 历史最高积分
    int32 score = 7;                   // 当前积分
    int32 inside_remain_add_count = 8; //局内剩余可添加物品次数
    map<int32, int32> map_merge_record = 15;  	// 合成记录 <等级，次数>	整个活动的
    map<int32, int32> map_merge_inside_record = 16;  // 合成记录 <等级，次数>	局内的最大值
    map<int32, int32> map_inside_item_count = 17;	// 单局剩余可用道具次数 <item_id, count>
}
