syntax = "proto3";

option csharp_namespace = "Net.Proto.Watermelon";
option go_package = "wx_game/msg";

// 单个大西瓜信息
message watermelon_entity
{
    int32 id = 1;
    int32 level = 2;
    float pos_x = 3;
    float pos_y = 4;
	  float angle = 5;
}

// 西瓜进度快照
message watermelon_record_snapshot
{
    repeated watermelon_entity records = 1;
}

// 请求游戏开始
message watermelon_start
{
    message request{
    }
    message response{
        int32 error_code = 1;
        watermelon_record_snapshot snapshot = 2;
        int32 stamina = 3;                          // 体力
        int64 stamina_tm = 4;                       // 体力刷新时间戳秒
        repeated watermelon_entity entity_lst = 5;   // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
        int32 history_score = 6;                 		// 历史最高积分
        int32 score = 7;                   // 当前积分
        map<int32, int32> map_item_count = 8;	//  剩余可用道具次数 <item_id, count>
        int32 remain_add_count = 9; //剩余可添加物品次数
        int32 fall_cnt = 10; //本局请求掉落数
    }
}

// 请求游戏结束
message watermelon_end
{
    message request{
    }
    message response{
        int32 error_code = 1;
    }
}

// 请求西瓜开始掉落
message watermelon_fall
{
    message request{
        int32 watermelon_id = 1;
        watermelon_record_snapshot snapshot = 2;
    }
    message response{
        int32 error_code = 1;
        int32 stamina = 2;                          // 体力(返回错误码也保证有值)
        int64 stamina_tm = 3;                       // 体力刷新时间戳秒
        repeated watermelon_entity entity_lst = 4;   // 下发后续N个西瓜，客户端判断过滤ID必须大于盘中所有的西瓜ID
        int32 fall_cnt = 5; //本局请求掉落数
    }
}

// 合并信息
message watermelon_merge_detail
{
    int32 from_id = 1;
    int32 to_id = 2;        // id小的合并到id大的
}

// 请求西瓜同步-包含合并
message watermelon_sync
{
    message request{
        repeated watermelon_merge_detail merge_lst = 1; // 合并先后顺序必须有序
        watermelon_record_snapshot snapshot = 2;
    }
    message response{
        int32 error_code = 1;
        int32 score = 2;                   // 当前积分
    }
}

// 使用道具
message watermelon_use_item
{
    message request{
        int32 item_id = 1;                     // 体力，消除，换位置，升级
        int32 item_num = 2;                    // 只有体力道具可以有多个
        repeated int32 watermelon_id_lst = 3; // 操作涉及的西瓜Id列表,没有则不填
        watermelon_record_snapshot snapshot = 4; // 使用道具后的快照
    }
    message response{
        int32 error_code = 1;
        int32 item_id = 2;
        int32 item_num = 3; // 剩余可用数量
    }
}

// 添加道具
message watermelon_add_item
{
    message request{
        int32 item_id = 1;
        int32 item_num = 2;
    }
    message response{
        int32 error_code = 1;
        int32 item_id = 2;
        int32 item_num = 3; // 剩余可用数量
        int32 remain_add_count = 4; //剩余可添加物品次数
    }
}
